import { isLineBlocked,getCoverSlot } from './cover.js';
const sprite=new Image();sprite.src='./assets/player.svg';
export const SQUAD_MODES=['FOLLOW','HOLD','ASSAULT','FOCUS'];
let squadMode='FOLLOW';
const SQUAD_NAMES=['Rook','Viper','Doc'];
function wireSquadCommands(){document.querySelectorAll('#squadCommands button').forEach((b,i)=>{b.classList.toggle('active',i===0);b.addEventListener('pointerdown',e=>{e.preventDefault();squadMode=b.dataset.command||'FOLLOW';window.squadMode=squadMode;document.querySelectorAll('#squadCommands button').forEach(x=>x.classList.toggle('active',x===b))})})}
if(typeof window!=='undefined'){window.squadMode='FOLLOW';if(document.readyState==='loading')addEventListener('DOMContentLoaded',wireSquadCommands);else wireSquadCommands()}
export function createAllies(){return[
{name:SQUAD_NAMES[0],x:-70,y:170,hp:80,maxHp:80,fire:.4,t:0,dead:false,deathTimer:0,deathDuration:.8,muzzle:0,hit:0,targetX:-70,targetY:170,moveTimer:.2,cover:null,speed:145,facingX:1,facingY:0,scale:.95},
{name:SQUAD_NAMES[1],x:75,y:185,hp:80,maxHp:80,fire:.9,t:.8,dead:false,deathTimer:0,deathDuration:.8,muzzle:0,hit:0,targetX:75,targetY:185,moveTimer:.5,cover:null,speed:150,facingX:-1,facingY:0,scale:.95},
{name:SQUAD_NAMES[2],x:0,y:260,hp:100,maxHp:100,fire:1.3,t:1.6,dead:false,deathTimer:0,deathDuration:.8,muzzle:0,hit:0,targetX:0,targetY:260,moveTimer:.8,cover:null,speed:125,facingX:1,facingY:0,scale:1}
]}
function nearestEnemy(a,enemies){let best=null,bd=Infinity;for(const e of enemies){if(e.dead)continue;const d=Math.hypot(a.x-e.x,a.y-e.y);if(d<bd){bd=d;best=e}}return[best,bd]}
function focusEnemy(player,enemies){let best=null,bd=Infinity;for(const e of enemies){if(e.dead)continue;const d=Math.hypot(player.x-e.x,player.y-e.y);if(d<bd){bd=d;best=e}}return[best,bd]}
function choosePosition(a,player,covers,allies,enemies,target,mode){const available=covers.filter(c=>Math.hypot(target.x-c.x,target.y-c.y)<760&&!allies.some(o=>o!==a&&!o.dead&&o.cover===c)&&!enemies.some(e=>!e.dead&&e.cover===c));if(!available.length){a.cover=null;a.targetX=player.x+(Math.random()-.5)*90;a.targetY=player.y+60+Math.random()*90;return}const desired=mode==='ASSAULT' ? 210 : mode==='FOCUS' ? 270 : 300;available.sort((u,v)=>Math.abs(Math.hypot(target.x-u.x,target.y-u.y)-desired)-Math.abs(Math.hypot(target.x-v.x,target.y-v.y)-desired));const c=available[0];a.cover=c;const slot=getCoverSlot(c,a,target);a.targetX=slot.x;a.targetY=slot.y}
export function updateAllies(allies,dt,player,covers,enemies,spawnProjectile,mode=squadMode){mode=mode||'FOLLOW';for(const a of allies){if(a.dead){a.deathTimer=Math.min(a.deathDuration,a.deathTimer+dt);continue}a.t+=dt;a.fire-=dt;a.muzzle=Math.max(0,a.muzzle-dt);a.hit=Math.max(0,a.hit-dt);a.moveTimer-=dt;let target,dist;if(mode==='FOCUS'){[target,dist]=focusEnemy(player,enemies)}else{[target,dist]=nearestEnemy(a,enemies)}if(!target){a.targetX=player.x+(a.x<player.x?-45:45);a.targetY=player.y+70;a.cover=null}else{const blocked=isLineBlocked(a,target,covers);if(a.moveTimer<=0){a.moveTimer=mode==='ASSAULT' ? .35 : mode==='FOCUS' ? .5 : .65+Math.random()*.45;if(mode==='HOLD'&&!a.cover)choosePosition(a,player,covers,allies,enemies,target,'HOLD');else if(mode!=='HOLD'&&(blocked||dist<210||!a.cover))choosePosition(a,player,covers,allies,enemies,target,mode)}if(mode==='FOLLOW'&&dist>520){a.cover=null;a.targetX=player.x+(a.x<player.x?-55:55);a.targetY=player.y+55+(a.y-player.y)*.15}if(mode==='ASSAULT'&&dist>250&&a.moveTimer<=0)choosePosition(a,player,covers,allies,enemies,target,'ASSAULT');if(mode==='FOCUS'&&dist>360&&a.moveTimer<=0)choosePosition(a,player,covers,allies,enemies,target,'FOCUS');if(mode==='HOLD'&&a.cover&&dist<520){a.targetX=a.x;a.targetY=a.y}const dx=a.targetX-a.x,dy=a.targetY-a.y,d=Math.hypot(dx,dy);if(d>7){a.facingX=dx/d;a.facingY=dy/d;const step=Math.min(d,a.speed*dt);a.x+=dx/d*step;a.y+=dy/d*step}else{a.targetX=a.x;a.targetY=a.y}const lineBlocked=isLineBlocked(a,target,covers);const fireGap=mode==='FOCUS' ? .42 : mode==='ASSAULT' ? .48 : .65;if(a.fire<=0&&dist<520&&(!lineBlocked||a.cover)){a.fire=fireGap+Math.random()*.28;a.facingX=(target.x-a.x)/(dist||1);a.facingY=(target.y-a.y)/(dist||1);a.muzzle=.1;a.hit=0;if(spawnProjectile)spawnProjectile(a,target)}}}}
export function drawAlly(ctx,a,iso){let[sx,sy]=iso(a.x,a.y),death=Math.min(1,a.deathTimer/a.deathDuration);ctx.save();ctx.translate(sx,sy+death*16);ctx.globalAlpha=1-death*.88;if(!a.dead&&a.hp<a.maxHp){ctx.fillStyle='#111';ctx.fillRect(-20,-67,40,5);ctx.fillStyle='#58a8ff';ctx.fillRect(-20,-67,40*Math.max(0,a.hp/a.maxHp),5)}if(a.hit>0&&!a.dead){ctx.globalAlpha=.55;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,-35,22,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1-death*.88}if(a.dead){ctx.rotate(death*1.5);ctx.scale(1-death*.14,1-death*.14)}const frame=a.dead?5:a.muzzle>0?4:a.cover?3:1+Math.floor(a.t*8)%2;
/* Mirror only the soldier sprite, never the UI label. */
ctx.save();ctx.scale(a.facingX<0?-1:1,1);ctx.filter='hue-rotate(155deg) saturate(1.35)';if(sprite.complete&&sprite.naturalWidth)ctx.drawImage(sprite,frame*64,0,64,64,-32*a.scale,-64*a.scale,64*a.scale,64*a.scale);else{ctx.filter='none';ctx.fillStyle='#477da8';ctx.fillRect(-13,-38,26,36);ctx.fillStyle='#9a9d9b';ctx.beginPath();ctx.arc(0,-48,10,0,Math.PI*2);ctx.fill()}if(a.muzzle>0&&!a.dead){ctx.filter='none';ctx.fillStyle='#ffe36b';ctx.beginPath();ctx.moveTo(30,-30);ctx.lineTo(45,-24);ctx.lineTo(34,-19);ctx.lineTo(37,-28);ctx.closePath();ctx.fill()}ctx.restore();
ctx.fillStyle='#fff';ctx.font='800 11px system-ui';ctx.textAlign='center';ctx.textBaseline='bottom';ctx.shadowColor='#000';ctx.shadowBlur=4;ctx.fillText(a.name||'ALLY',0,-70*a.scale);ctx.restore()}
