import { isLineBlocked,getCoverSlot,getHitChance,chooseCoverPeek } from './cover.js?v=20260904-34';
import { weaponCopy } from './weapons.js';

export const SQUAD_MODES=['FOLLOW','HOLD','ASSAULT','FOCUS'];
var squadMode='FOLLOW',healthHud=null;
var SQUAD=[{name:'Rook',weapon:'rifle',role:'assault',speed:205,regen:4,hp:80},{name:'Viper',weapon:'smg',role:'flanker',speed:235,regen:4,hp:80},{name:'Doc',weapon:'dmr',role:'marksman',speed:180,regen:5,hp:100}];
function rand(a,b){return a+Math.random()*(b-a)}
function wireSquadCommands(){var buttons=document.querySelectorAll('#squadCommands button');buttons.forEach(function(b,i){b.classList.toggle('active',i===0);b.addEventListener('pointerdown',function(e){e.preventDefault();squadMode=b.dataset.command||'FOLLOW';window.squadMode=squadMode;buttons.forEach(function(x){x.classList.toggle('active',x===b)})})})}
function ensureHealthHud(){if(healthHud)return healthHud;healthHud=document.createElement('div');healthHud.id='allyHealth';healthHud.style.cssText='position:fixed;left:12px;top:calc(env(safe-area-inset-top) + 62px);width:145px;padding:7px 8px;border:1px solid #ffffff22;border-radius:9px;background:#101714cc;backdrop-filter:blur(4px);z-index:5;pointer-events:none;font:800 10px system-ui;color:#e8eee9;letter-spacing:.6px;text-shadow:0 1px 3px #000';document.body.appendChild(healthHud);return healthHud}
function updateHealthHud(allies){var h=ensureHealthHud();h.innerHTML='<div style="font-size:9px;color:#8fb7c8;letter-spacing:1.2px;margin-bottom:4px">SQUAD STATUS</div>'+allies.map(function(a){var pct=Math.round(Math.max(0,a.hp)/a.maxHp*100),label=a.dead?'KIA':a.downed?'DOWNED':pct+'%',color=a.dead?'#666':pct>55?'#61b86b':pct>25?'#d6b74d':'#d85b50';return '<div style="margin:2px 0 5px;opacity:'+(a.dead?'.4':'1')+'"><div style="display:flex;justify-content:space-between"><span>'+a.name+' · '+a.weapon.short+'</span><span>'+label+'</span></div><div style="height:4px;background:#303733;border-radius:3px;overflow:hidden"><div style="height:100%;width:'+pct+'%;background:'+color+'"></div></div></div>'}).join('')}
if(typeof window!=='undefined'){window.squadMode='FOLLOW';if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',wireSquadCommands);else wireSquadCommands()}

export function createAllies(){var starts=[[-70,170],[75,185],[0,260]];var allies=SQUAD.map(function(s,i){var pos=starts[i],w=weaponCopy(s.weapon);return{name:s.name,role:s.role,weapon:w,x:pos[0],y:pos[1],hp:s.hp,maxHp:s.hp,lastHp:s.hp,fire:.4+i*.4,t:0,dead:false,permadead:false,downed:false,downTimer:0,downDuration:11,reviveTimer:0,reviveDuration:2.5,deathTimer:0,deathDuration:.8,muzzle:0,hit:0,targetX:pos[0],targetY:pos[1],cover:null,coverSlotIndex:i,speed:s.speed,facingX:i===1?-1:1,facingY:0,scale:1,timeSinceDamage:99,regenDelay:3,regenRate:s.regen,callout:'',calloutTimer:0,lastCalloutHealth:s.hp,reloadTimer:0,reloading:false,flankSide:i===1?-1:1,combatState:'seeking',combatTimer:0,shotsLeft:0,coverCycles:0,coverAnchorX:pos[0],coverAnchorY:pos[1],peekX:pos[0],peekY:pos[1],exposed:false,coverCommit:0,repathTimer:0,underFireTimer:0,lastCoverId:null,angleFails:0}});if(typeof window!=='undefined')window.__battleAllies=allies;return allies}
function say(a,text,duration){a.callout=text;a.calloutTimer=duration||1.8}
function nearestEnemy(a,enemies){var best=null,bd=Infinity;enemies.forEach(function(e){if(e.dead)return;var d=Math.hypot(a.x-e.x,a.y-e.y);if(d<bd){bd=d;best=e}});return{target:best,dist:bd}}
function focusEnemy(player,enemies){var best=null,bd=Infinity;enemies.forEach(function(e){if(e.dead)return;var d=Math.hypot(player.x-e.x,player.y-e.y);if(d<bd){bd=d;best=e}});return{target:best,dist:bd}}
function weakestEnemy(enemies){var best=null,score=-Infinity;enemies.forEach(function(e){if(e.dead)return;var s=(1-e.hp/e.maxHp)*2+Math.random()*.12;if(s>score){score=s;best=e}});return best}
function occupancy(c,allies,a){var n=0;allies.forEach(function(o){if(o!==a&&!o.dead&&!o.downed&&o.cover===c)n++});return n}
function desiredRange(a,mode){if(a.role==='marksman')return 760;if(a.role==='flanker')return 470;if(mode==='ASSAULT')return 390;if(mode==='HOLD')return 570;return 540}
function scoreCover(a,c,target,player,covers,allies,mode){var travel=Math.hypot(c.x-a.x,c.y-a.y),td=Math.hypot(c.x-target.x,c.y-target.y),desired=desiredRange(a,mode),users=occupancy(c,allies,a);if(travel>780||users>=3)return 1e9;var temp={x:a.x,y:a.y,coverSlotIndex:users%3};var anchor=getCoverSlot(c,temp,target);var peek=chooseCoverPeek(c,temp,target,covers);var anchorProtected=isLineBlocked(anchor,target,covers);var peekClear=!isLineBlocked(peek,target,covers);var score=travel*.62+Math.abs(td-desired)*.78+users*230+(anchorProtected?-120:220)+(peekClear?-180:380);if(c.id===a.lastCoverId)score+=170;if(mode==='FOLLOW'){var pd=Math.hypot(c.x-player.x,c.y-player.y);score+=Math.max(0,pd-520)*.7}if(a.role==='flanker'){var side=(c.x-player.x)*a.flankSide;score+=side>80?-80:120}if(c.type==='wide'||c.type==='car')score-=45;if(c.segments&&c.segments.length>1)score-=55;return score}
function choosePosition(a,player,covers,allies,target,mode){var ranked=[];for(var i=0;i<covers.length;i++){var c=covers[i],s=scoreCover(a,c,target,player,covers,allies,mode);if(s<1e9)ranked.push({c:c,s:s})}ranked.sort(function(u,v){return u.s-v.s});if(!ranked.length){a.cover=null;a.exposed=true;a.combatState='seeking';var dx=target.x-a.x,dy=target.y-a.y,d=Math.hypot(dx,dy)||1;a.targetX=a.x+dx/d*150;a.targetY=a.y+dy/d*150;a.repathTimer=.9;return false}var pick=ranked[Math.floor(Math.random()*Math.min(2,ranked.length))].c;a.lastCoverId=a.cover?a.cover.id:a.lastCoverId;a.cover=pick;var users=occupancy(pick,allies,a);a.coverSlotIndex=users%3;var slot=getCoverSlot(pick,a,target);var peek=chooseCoverPeek(pick,a,target,covers);a.coverAnchorX=slot.x;a.coverAnchorY=slot.y;a.peekX=peek.x;a.peekY=peek.y;a.targetX=slot.x;a.targetY=slot.y;a.combatState='seeking';a.exposed=false;a.coverCommit=rand(3.8,6.2);a.coverCycles=0;a.angleFails=isLineBlocked(peek,target,covers)?1:0;a.repathTimer=rand(.45,.75);return true}
function enterCovered(a){a.combatState='covered';a.combatTimer=rand(.45,.85);a.exposed=false;a.targetX=a.coverAnchorX;a.targetY=a.coverAnchorY;a.coverCycles++}
function enterPeeking(a,target,covers){var p=chooseCoverPeek(a.cover,a,target,covers);a.peekX=p.x;a.peekY=p.y;a.targetX=p.x;a.targetY=p.y;a.combatState='peeking';a.combatTimer=1.1;a.exposed=false}
function enterFiring(a){a.combatState='firing';a.combatTimer=rand(.55,1.0);a.shotsLeft=2+Math.floor(Math.random()*3);a.exposed=true;a.targetX=a.peekX;a.targetY=a.peekY}
function enterTucking(a){a.combatState='tucking';a.combatTimer=.8;a.targetX=a.coverAnchorX;a.targetY=a.coverAnchorY;a.exposed=true}
function separateFromSquad(a,allies){var sx=0,sy=0,n=0;allies.forEach(function(o){if(o===a||o.dead||o.downed)return;var dx=a.x-o.x,dy=a.y-o.y,d=Math.hypot(dx,dy);if(d<115&&d>0){sx+=dx/d*(115-d);sy+=dy/d*(115-d);n++}});return n?{x:sx/n,y:sy/n}:null}
function tryRevive(a,allies,player,dt){var best=null,bd=Infinity;allies.forEach(function(o){if(o===a||o.dead||!o.downed)return;var d=Math.hypot(a.x-o.x,a.y-o.y);if(d<64&&d<bd){bd=d;best=o}});if(player&&player.downed&&!player.dead){var pd=Math.hypot(a.x-player.x,a.y-player.y);if(pd<64&&pd<bd){bd=pd;best=player}}if(!best){a.reviveTimer=0;return false}a.targetX=a.x;a.targetY=a.y;a.cover=null;a.exposed=false;a.reviveTimer+=dt;if(a.reviveTimer>=a.reviveDuration){a.reviveTimer=0;if(best.revive)best.revive();say(a,'BACK ON YOUR FEET!',1.5);if(best!==player)say(best,"I'M UP!",1.4)}return true}
function moveToward(a,dt){var dx=a.targetX-a.x,dy=a.targetY-a.y,d=Math.hypot(dx,dy);if(d<=6){a.x=a.targetX;a.y=a.targetY;return d}a.facingX=dx/d;a.facingY=dy/d;var step=Math.min(d,a.speed*dt);a.x+=dx/d*step;a.y+=dy/d*step;return d}

export function updateAllies(allies,dt,player,covers,enemies,spawnProjectile,mode){mode=mode||squadMode||'FOLLOW';updateHealthHud(allies);for(var i=0;i<allies.length;i++){var a=allies[i];if(a.dead){a.deathTimer=Math.min(a.deathDuration,a.deathTimer+dt);continue}a.t+=dt;a.fire-=dt;a.muzzle=Math.max(0,a.muzzle-dt);a.hit=Math.max(0,a.hit-dt);a.calloutTimer=Math.max(0,a.calloutTimer-dt);a.timeSinceDamage+=dt;a.coverCommit=Math.max(0,a.coverCommit-dt);a.repathTimer=Math.max(0,a.repathTimer-dt);a.underFireTimer=Math.max(0,a.underFireTimer-dt);if(a.hp<a.lastHp){a.timeSinceDamage=0;a.underFireTimer=1.7;if(a.hp<a.maxHp*.35&&a.calloutTimer<=0)say(a,"I'M INJURED",1.6)}a.lastHp=a.hp;if(a.hp<=0&&!a.downed){a.downed=true;a.downTimer=0;a.hp=0;a.exposed=false;say(a,"I'M DOWNED",1.7)}if(a.downed){a.downTimer+=dt;if(a.downTimer>=a.downDuration){a.permadead=true;a.dead=true;a.downed=false;a.deathTimer=0}continue}if(a.hp<a.maxHp&&a.timeSinceDamage>=a.regenDelay)a.hp=Math.min(a.maxHp,a.hp+a.regenRate*dt);if(a.reloading){a.reloadTimer-=dt;if(a.reloadTimer<=0){a.reloading=false;a.weapon.ammo=a.weapon.magazine}}if(tryRevive(a,allies,player,dt))continue;
var pick,target=null,dist=Infinity;if(a.role==='marksman'&&mode!=='ASSAULT'){target=weakestEnemy(enemies);dist=target?Math.hypot(a.x-target.x,a.y-target.y):Infinity}else if(mode==='FOCUS'){pick=focusEnemy(player,enemies);target=pick.target;dist=pick.dist}else{pick=nearestEnemy(a,enemies);target=pick.target;dist=pick.dist}if(!target){a.cover=null;a.exposed=false;a.combatState='seeking';a.targetX=player.x+(a.role==='flanker'?a.flankSide*150:(a.x<player.x?-80:80));a.targetY=player.y+100+(a.role==='marksman'?-70:70);moveToward(a,dt);continue}
var currentBad=false;if(a.cover){var cd=Math.hypot(a.cover.x-target.x,a.cover.y-target.y),desired=desiredRange(a,mode);currentBad=cd<Math.max(220,desired*.52)||cd>a.weapon.range*1.18||a.angleFails>=2;if(a.underFireTimer>0&&a.coverCycles>=2)currentBad=true}if(!a.cover||((currentBad||a.coverCycles>=4)&&a.coverCommit<=0)){if(a.repathTimer<=0)choosePosition(a,player,covers,allies,target,mode)}if(mode==='HOLD'&&a.cover)currentBad=false;if(mode==='FOLLOW'&&Math.hypot(a.x-player.x,a.y-player.y)>900&&a.coverCommit<=0){a.cover=null;a.repathTimer=0;choosePosition(a,player,covers,allies,target,mode)}
var before=moveToward(a,dt);if(a.cover){if(a.combatState==='seeking'&&before<=14)enterCovered(a);else if(a.combatState==='covered'){a.combatTimer-=dt;a.exposed=false;a.targetX=a.coverAnchorX;a.targetY=a.coverAnchorY;if(a.combatTimer<=0&&dist<a.weapon.range*1.08)enterPeeking(a,target,covers)}else if(a.combatState==='peeking'){if(before<=10){if(isLineBlocked(a,target,covers)){a.angleFails++;enterTucking(a)}else{a.angleFails=0;enterFiring(a)}}else{a.combatTimer-=dt;if(a.combatTimer<=0){a.angleFails++;enterTucking(a)}}}else if(a.combatState==='firing'){a.combatTimer-=dt;a.exposed=true;a.targetX=a.peekX;a.targetY=a.peekY;if(a.combatTimer<=0||a.shotsLeft<=0)enterTucking(a)}else if(a.combatState==='tucking'){a.combatTimer-=dt;if(before<24)a.exposed=false;if(before<=10||a.combatTimer<=0)enterCovered(a)}}else{a.exposed=true}
var sep=separateFromSquad(a,allies);if(sep&&a.combatState==='seeking'&&!a.cover){a.targetX+=sep.x*.45;a.targetY+=sep.y*.45}
var lineBlocked=isLineBlocked(a,target,covers),chance=Math.max(12,Math.min(98,getHitChance(a,target,covers)+a.weapon.accuracy));a.lastHitChance=chance;if(a.weapon.ammo<=0&&!a.reloading){a.reloading=true;a.reloadTimer=a.weapon.reload;say(a,'RELOADING',1.1)}var canFire=dist<a.weapon.range&&!a.reloading&&((a.cover&&a.combatState==='firing')||!a.cover)&&!lineBlocked;if(a.fire<=0&&canFire){a.fire=a.weapon.cooldown*(a.role==='flanker'?.9:1.05)+Math.random()*.16;a.facingX=(target.x-a.x)/(dist||1);a.facingY=(target.y-a.y)/(dist||1);a.muzzle=.1;if(a.cover)a.shotsLeft--;if(spawnProjectile&&Math.random()*100<chance)spawnProjectile(a,target,'ally',a.weapon.damage)}}}
