import { isLineBlocked, getHitChance } from './cover.js?v=20260904-35';
import { weaponCopy } from './weapons.js';
import { pickTacticalCover, applyCoverChoice, moveTowardTarget, faceThreat, coverStillUseful, peekPoint } from './combatAI.js?v=20260904-35';
import { CHARACTER_STATS, mitigateDamage } from './combatStats.js?v=20260905-49';

export const SQUAD_MODES=['FOLLOW','HOLD','ASSAULT','FOCUS'];
var squadMode='FOLLOW',healthHud=null;
var SQUAD=[
  {name:'Rook',weapon:'rifle',role:'assault',speed:205,regen:4,hp:CHARACTER_STATS.Rook.hp,defense:CHARACTER_STATS.Rook.defense},
  {name:'Viper',weapon:'smg',role:'flanker',speed:235,regen:4,hp:CHARACTER_STATS.Viper.hp,defense:CHARACTER_STATS.Viper.defense},
  {name:'Doc',weapon:'dmr',role:'marksman',speed:180,regen:5,hp:CHARACTER_STATS.Doc.hp,defense:CHARACTER_STATS.Doc.defense}
];
function rand(a,b){return a+Math.random()*(b-a)}
function wireSquadCommands(){var buttons=document.querySelectorAll('#squadCommands button');buttons.forEach(function(b,i){b.classList.toggle('active',i===0);b.addEventListener('pointerdown',function(e){e.preventDefault();squadMode=b.dataset.command||'FOLLOW';window.squadMode=squadMode;buttons.forEach(function(x){x.classList.toggle('active',x===b)})})})}
function ensureHealthHud(){if(healthHud)return healthHud;healthHud=document.createElement('div');healthHud.id='allyHealth';healthHud.style.cssText='position:fixed;left:12px;top:calc(env(safe-area-inset-top) + 104px);width:145px;padding:7px 8px;border:1px solid #ffffff22;border-radius:9px;background:#101714cc;backdrop-filter:blur(4px);z-index:5;pointer-events:none;font:800 10px system-ui;color:#e8eee9;letter-spacing:.6px;text-shadow:0 1px 3px #000';document.body.appendChild(healthHud);return healthHud}
function updateHealthHud(allies){var h=ensureHealthHud();h.innerHTML='<div style="font-size:9px;color:#8fb7c8;letter-spacing:1.2px;margin-bottom:4px">SQUAD STATUS</div>'+allies.map(function(a){var pct=Math.round(Math.max(0,a.hp)/a.maxHp*100),label=a.dead?'KIA':a.downed?'DOWNED':pct+'%',color=a.dead?'#666':pct>55?'#61b86b':pct>25?'#d6b74d':'#d85b50';return '<div style="margin:2px 0 5px;opacity:'+(a.dead?'.4':'1')+'"><div style="display:flex;justify-content:space-between"><span>'+a.name+' · '+a.weapon.short+'</span><span>'+label+'</span></div><div style="font-size:8px;color:#9fb0b6;margin:2px 0">HP '+Math.ceil(a.hp)+'/'+a.maxHp+' · DEF '+a.defense+'</div><div style="height:4px;background:#303733;border-radius:3px;overflow:hidden"><div style="height:100%;width:'+pct+'%;background:'+color+'"></div></div></div>'}).join('')}
if(typeof window!=='undefined'){window.squadMode='FOLLOW';if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',wireSquadCommands);else wireSquadCommands()}
export function createAllies(){var starts=[[-70,170],[75,185],[0,260]],chosen=(typeof window!=='undefined'&&window.__selectedLoadout)||{};var allies=SQUAD.map(function(s,i){var pos=starts[i],w=weaponCopy(chosen[s.name]||s.weapon);return{name:s.name,role:s.role,weapon:w,x:pos[0],y:pos[1],hp:s.hp,maxHp:s.hp,defense:s.defense,lastHp:s.hp,fire:.4+i*.4,t:0,dead:false,permadead:false,downed:false,downTimer:0,downDuration:11,reviveTimer:0,reviveDuration:2.5,deathTimer:0,deathDuration:.8,muzzle:0,hit:0,targetX:pos[0],targetY:pos[1],moveTimer:.2+i*.3,cover:null,coverSlotIndex:i,speed:s.speed,facingX:i===1?-1:1,facingY:0,scale:1,timeSinceDamage:99,regenDelay:3,regenRate:s.regen,callout:'',calloutTimer:0,lastCalloutHealth:s.hp,reloadTimer:0,reloading:false,flankSide:i===1?-1:1,combatState:'seeking',combatTimer:0,shotsLeft:0,coverCycles:0,coverAnchorX:pos[0],coverAnchorY:pos[1],exposed:true,lastCoverId:null,repositionCooldown:0}});if(typeof window!=='undefined')window.__battleAllies=allies;return allies}
function say(a,text,duration){a.callout=text;a.calloutTimer=duration||1.8}
function nearestEnemy(a,enemies){var best=null,bd=Infinity;enemies.forEach(function(e){if(e.dead)return;var d=Math.hypot(a.x-e.x,a.y-e.y);if(d<bd){bd=d;best=e}});return{target:best,dist:bd}}
function focusEnemy(player,enemies){var best=null,bd=Infinity;enemies.forEach(function(e){if(e.dead)return;var d=Math.hypot(player.x-e.x,player.y-e.y);if(d<bd){bd=d;best=e}});return{target:best,dist:bd}}
function weakestEnemy(enemies){var best=null;enemies.forEach(function(e){if(!e.dead&&(!best||e.hp<best.hp))best=e});return best}
function reload(a){if(a.reloading)return;a.reloading=true;a.reloadTimer=a.weapon.reload;say(a,'RELOADING',1.1)}
function shoot(a,e,spawnProjectile,covers){if(a.dead||a.downed||a.reloading||a.weapon.ammo<=0)return;if(a.weapon.fireCooldown>0)return;var chance=Math.max(5,Math.min(96,getHitChance(a,e,covers)+a.weapon.accuracy)),hit=Math.random()*100<chance;a.weapon.ammo--;a.weapon.fireCooldown=a.weapon.cooldown;a.muzzle=.12;a.shotsLeft=Math.max(0,(a.shotsLeft||1)-1);if(spawnProjectile)spawnProjectile(a,e,'ally',hit?a.weapon.damage:0);if(hit){var dealt=mitigateDamage(a.weapon.damage,e.defense);e.hp=Math.max(0,e.hp-dealt);e.lastDamageTaken=dealt;e.hit=.18;if(e.hp<=0){e.hp=0;e.dead=true;e.deathTimer=0;say(a,'TARGET DOWN!',1.4)}}if(a.weapon.ammo<=0)reload(a)}
function updateRevive(a,allies,player,dt){var targets=allies.concat([player]),best=null,bd=Infinity;targets.forEach(function(t){if(t===a||!t.downed||t.dead)return;var d=Math.hypot(a.x-t.x,a.y-t.y);if(d<bd){bd=d;best=t}});if(!best)return false;if(bd>62){a.targetX=best.x;a.targetY=best.y;moveTowardTarget(a,dt);return true}best.reviveTimer=(best.reviveTimer||0)+dt;if(best.reviveTimer>=best.reviveDuration){if(typeof best.revive==='function')best.revive();else{best.downed=false;best.hp=Math.max(30,Math.round(best.maxHp*.4));best.reviveTimer=0;best.timeSinceDamage=0}say(a,'BACK UP!',1.5)}return true}
export function updateAllies(allies,dt,player,covers,enemies,spawnProjectile,mode){squadMode=mode||window.squadMode||squadMode;updateHealthHud(allies);allies.forEach(function(a){a.t+=dt;a.hit=Math.max(0,a.hit-dt);a.muzzle=Math.max(0,a.muzzle-dt);a.calloutTimer=Math.max(0,a.calloutTimer-dt);a.timeSinceDamage+=dt;if(a.weapon.fireCooldown>0)a.weapon.fireCooldown=Math.max(0,a.weapon.fireCooldown-dt);if(a.dead){a.deathTimer+=dt;return}if(a.hp<=0&&!a.downed){a.downed=true;a.downTimer=0;a.hp=0;say(a,'MAN DOWN',1.7)}if(a.downed){a.downTimer+=dt;if(a.downTimer>=a.downDuration){a.dead=true;a.downed=false;a.deathTimer=0}return}if(a.reloading){a.reloadTimer-=dt;if(a.reloadTimer<=0){a.reloading=false;a.weapon.ammo=a.weapon.magazine}}if(a.hp<a.maxHp&&a.timeSinceDamage>a.regenDelay)a.hp=Math.min(a.maxHp,a.hp+a.regenRate*dt);if(updateRevive(a,allies,player,dt))return;var pick=squadMode==='FOCUS'&&player.aimTarget&&!player.aimTarget.dead?{target:player.aimTarget,dist:Math.hypot(a.x-player.aimTarget.x,a.y-player.aimTarget.y)}:nearestEnemy(a,enemies),e=pick.target,d=pick.dist;if(!e){a.targetX=player.x+(a.coverSlotIndex-1)*70;a.targetY=player.y+90;moveTowardTarget(a,dt);return}faceThreat(a,e);if(squadMode==='FOLLOW'&&Math.hypot(a.x-player.x,a.y-player.y)>330){a.targetX=player.x+(a.coverSlotIndex-1)*65;a.targetY=player.y+85;moveTowardTarget(a,dt);return}if(squadMode==='HOLD'&&a.combatState==='seeking'){a.coverAnchorX=a.x;a.coverAnchorY=a.y}a.repositionCooldown=Math.max(0,a.repositionCooldown-dt);var blocked=isLineBlocked(a,e,covers);if((!a.cover||!coverStillUseful(a,e,covers)||blocked)&&a.repositionCooldown<=0&&squadMode!=='HOLD'){var choice=pickTacticalCover(a,e,covers,{maxTravel:squadMode==='ASSAULT'?650:480,desiredRange:Math.min(a.weapon.range*.72,700)});if(choice){applyCoverChoice(a,choice);a.repositionCooldown=.8}}if(a.cover&&a.combatState==='seeking'){moveTowardTarget(a,dt);if(Math.hypot(a.x-a.targetX,a.y-a.targetY)<18){a.combatState='covered';a.exposed=false;a.coverCycles=0}return}if(a.cover){a.combatTimer-=dt;if(a.combatState==='covered'&&a.combatTimer<=0){a.combatState='exposed';a.exposed=true;a.combatTimer=.55+Math.random()*.5;a.shotsLeft=2+Math.floor(Math.random()*3);var pp=peekPoint(a,a.cover,e);a.x=pp.x;a.y=pp.y}else if(a.combatState==='exposed'){if(d<=a.weapon.range)shoot(a,e,spawnProjectile,covers);if(a.combatTimer<=0||a.shotsLeft<=0){a.combatState='covered';a.exposed=false;a.combatTimer=.55+Math.random()*.7;a.coverCycles++}}return}if(d>a.weapon.range*.8&&squadMode!=='HOLD'){a.targetX=e.x;a.targetY=e.y;moveTowardTarget(a,dt)}else shoot(a,e,spawnProjectile,covers)})}
