import { isLineBlocked,getCoverSlot,getHitChance } from './cover.js';
const sprite=new Image();sprite.src='./assets/player.svg';
const DRAW_SCALE=.40;
export const SQUAD_MODES=['FOLLOW','HOLD','ASSAULT','FOCUS'];
let squadMode='FOLLOW',healthHud=null;
const SQUAD_NAMES=['Rook','Viper','Doc'];
function wireSquadCommands(){document.querySelectorAll('#squadCommands button').forEach(function(b,i){b.classList.toggle('active',i===0);b.addEventListener('pointerdown',function(e){e.preventDefault();squadMode=b.dataset.command||'FOLLOW';window.squadMode=squadMode;document.querySelectorAll('#squadCommands button').forEach(function(x){x.classList.toggle('active',x===b)})})})}
function ensureHealthHud(){if(healthHud)return healthHud;healthHud=document.createElement('div');healthHud.id='allyHealth';healthHud.style.cssText='position:fixed;left:12px;top:calc(env(safe-area-inset-top) + 104px);width:122px;padding:7px 8px;border:1px solid #ffffff22;border-radius:9px;background:#101714cc;backdrop-filter:blur(4px);z-index:5;pointer-events:none;font:800 10px system-ui;color:#e8eee9;letter-spacing:.6px;text-shadow:0 1px 3px #000';document.body.appendChild(healthHud);return healthHud}
function updateHealthHud(allies){const h=ensureHealthHud();h.innerHTML='<div style="font-size:9px;color:#8fb7c8;letter-spacing:1.2px;margin-bottom:4px">SQUAD STATUS</div>'+allies.map(function(a){var pct=Math.round(Math.max(0,a.hp)/a.maxHp*100);var label=a.dead?'KIA':a.downed?'DOWNED':pct+'%';return '<div style="margin:2px 0 5px;opacity:'+(a.dead?'.4':'1')+'"><div style="display:flex;justify-content:space-between"><span>'+a.name+'</span><span>'+label+'</span></div><div style="height:4px;background:#303733;border-radius:3px;overflow:hidden"><div style="height:100%;width:'+pct+'%;background:'+(a.dead?'#666':pct>55?'#61b86b':pct>25?'#d6b74d':'#d85b50')+'"></div></div></div>'}).join('')}
if(typeof window!=='undefined'){window.squadMode='FOLLOW';if(document.readyState==='loading')addEventListener('DOMContentLoaded',wireSquadCommands);else wireSquadCommands()}
export function createAllies(){return[
{name:SQUAD_NAMES[0],x:-70,y:170,hp:80,maxHp:80,fire:.4,t:0,dead:false,permadead:false,downed:false,downTimer:0,downDuration:11,reviveTimer:0,reviveDuration:2.5,deathTimer:0,deathDuration:.8,muzzle:0,hit:0,targetX:-70,targetY:170,moveTimer:.2,cover:null,coverSlotIndex:0,speed:145,facingX:1,facingY:0,scale:1,timeSinceDamage:99,regenDelay:3,regenRate:4,callout:'',calloutTimer:0,lastCalloutHealth:80},
{name:SQUAD_NAMES[1],x:75,y:185,hp:80,maxHp:80,fire:.9,t:.8,dead:false,permadead:false,downed:false,downTimer:0,downDuration:11,reviveTimer:0,reviveDuration:2.5,deathTimer:0,deathDuration:.8,muzzle:0,hit:0,targetX:75,targetY:185,moveTimer:.5,cover:null,coverSlotIndex:1,speed:150,facingX:-1,facingY:0,scale:1,timeSinceDamage:99,regenDelay:3,regenRate:4,callout:'',calloutTimer:0,lastCalloutHealth:80},
{name:SQUAD_NAMES[2],x:0,y:260,hp:100,maxHp:100,fire:1.3,t:1.6,dead:false,permadead:false,downed:false,downTimer:0,reviveTimer:0,reviveDuration:2.5,deathTimer:0,deathDuration:.8,muzzle:0,hit:0,targetX:0,targetY:260,moveTimer:.8,cover:null,coverSlotIndex:2,speed:125,facingX:1,facingY:0,scale:1,timeSinceDamage:99,regenDelay:3,regenRate:5,callout:'',calloutTimer:0,lastCalloutHealth:100}
]}
function say(a,text,duration){a.callout=text;a.calloutTimer=duration||1.8}
function nearestEnemy(a,enemies){let best=null,bd=Infinity;for(const e of enemies){if(e.dead)continue;const d=Math.hypot(a.x-e.x,a.y-e.y);if(d<bd){bd=d;best=e}}return[best,bd]}
function focusEnemy(player,enemies){let best=null,bd=Infinity;for(const e of enemies){if(e.dead)continue;const d=Math.hypot(player.x-e.x,player.y-e.y);if(d<bd){bd=d;best=e}}return[best,bd]}
function choosePosition(a,player,covers,allies,enemies,target,mode){const available=covers.filter(function(c){return Math.hypot(target.x-c.x,target.y-c.y)<760&&!enemies.some(function(e){return !e.dead&&!e.downed&&e.cover===c})});if(!available.length){a.cover=null;a.targetX=player.x+(Math.random()-.5)*90;a.targetY=player.y+60+Math.random()*90;return}const desired=mode==='ASSAULT'?210:mode==='FOCUS'?270:300;available.sort(function(u,v){return Math.abs(Math.hypot(target.x-u.x,target.y-u.y)-desired)-Math.abs(Math.hypot(target.x-v.x,target.y-v.y)-desired)});const c=available[0];a.cover=c;const users=allies.filter(function(o){return o!==a&&!o.dead&&!o.downed&&o.cover===c});a.coverSlotIndex=users.length%3;const slot=getCoverSlot(c,a,target);a.targetX=slot.x;a.targetY=slot.y}
function tryRevive(a,allies,player,dt){let best=null,bd=Infinity;for(const o of allies){if(o===a||o.dead||!o.downed)continue;const d=Math.hypot(a.x-o.x,a.y-o.y);if(d<58&&d<bd){bd=d;best=o}}if(player&&player.downed&&!player.dead){const d=Math.hypot(a.x-player.x,a.y-player.y);if(d<58&&d<bd){bd=d;best=player}}if(!best){a.reviveTimer=0;return false}a.targetX=a.x;a.targetY=a.y;a.cover=null;a.reviveTimer+=dt;if(a.reviveTimer>=a.reviveDuration){a.reviveTimer=0;if(best.revive)best.revive();say(a,'BACK ON YOUR FEET!',1.5);if(best!==player)say(best,'I\'M UP!',1.4)}return true}
export function updateAllies(allies,dt,player,covers,enemies,spawnProjectile,mode=squadMode){mode=mode||'FOLLOW';updateHealthHud(allies);for(const a of allies){if(a.dead){if(!a.permadead&&a.hp<=0&&!a.downed){a.dead=false;a.downed=true;a.downTimer=0;say(a,'I\'M DOWNED',1.7)}else{a.deathTimer=Math.min(a.deathDuration,a.deathTimer+dt);continue}}a.t+=dt;a.fire-=dt;a.muzzle=Math.max(0,a.muzzle-dt);a.hit=Math.max(0,a.hit-dt);a.calloutTimer=Math.max(0,a.calloutTimer-dt);a.timeSinceDamage+=dt;if(a.downed){a.downTimer+=dt;if(a.downTimer>=a.downDuration){a.permadead=true;a.dead=true;a.deathTimer=0;say(a,'I\'M GONE!',1.5)}continue}if(a.hp<a.maxHp&&a.timeSinceDamage>=a.regenDelay)a.hp=Math.min(a.maxHp,a.hp+a.regenRate*dt);if(tryRevive(a,allies,player,dt))continue;a.moveTimer-=dt;let target,dist;if(mode==='FOCUS'){[target,dist]=focusEnemy(player,enemies)}else{[target,dist]=nearestEnemy(a,enemies)}if(!target){a.targetX=player.x+(a.x<player.x?-45:45);a.targetY=player.y+70;a.cover=null}else{const blocked=isLineBlocked(a,target,covers);if(a.moveTimer<=0){a.moveTimer=mode==='ASSAULT'?0.35:mode==='FOCUS'?0.5:0.65+Math.random()*.45;if(mode==='HOLD'&&!a.cover)choosePosition(a,player,covers,allies,enemies,target,'HOLD');else if(mode!=='HOLD'&&(blocked||dist<210||!a.cover))choosePosition(a,player,covers,allies,enemies,target,mode)}if(mode==='FOLLOW'&&dist>520){a.cover=null;a.targetX=player.x+(a.x<player.x?-55:55);a.targetY=player.y+55+(a.y-player.y)*.15}if(mode==='ASSAULT'&&dist>250&&a.moveTimer<=0)choosePosition(a,player,covers,allies,enemies,target,'ASSAULT');if(mode==='FOCUS'&&dist>360&&a.moveTimer<=0)choosePosition(a,player,covers,allies,enemies,target,'FOCUS');if(mode==='HOLD'&&a.cover&&dist<520){a.targetX=a.x;a.targetY=a.y}const dx=a.targetX-a.x,dy=a.targetY-a.y,d=Math.hypot(dx,dy);if(d>7){a.facingX=dx/d;a.facingY=dy/d;const step=Math.min(d,a.speed*dt);a.x+=dx/d*step;a.y+=dy/d*step}else{a.targetX=a.x;a.targetY=a.y}const lineBlocked=isLineBlocked(a,target,covers),fireGap=mode==='FOCUS'?0.55:mode==='ASSAULT'?0.62:0.82,chance=Math.max(18,getHitChance(a,target,covers)-10);a.lastHitChance=chance;if(a.fire<=0&&dist<520&&(!lineBlocked||a.cover)){a.fire=fireGap+Math.random()*.45;a.facingX=(target.x-a.x)/(dist||1);a.facingY=(target.y-a.y)/(dist||1);a.muzzle=.1;a.hit=0;if(spawnProjectile&&Math.random()*100<chance){spawnProjectile(a,target);if(a.calloutTimer<=0&&Math.random()<.22)say(a,'SUPPRESSING FIRE',1.25)}}}if(a.calloutTimer<=0){if(a.hp<a.maxHp*.35&&a.lastCalloutHealth>=a.maxHp*.35){say(a,'I\'M INJURED',1.6);a.lastCalloutHealth=a.hp}else if(a.cover&&Math.random()<.008)say(a,'I\'M PINNED',1.5);else if(mode==='ASSAULT'&&Math.random()<.006)say(a,'PUSH!',1.3);else if(mode==='FOLLOW'&&Math.random()<.004&&dist>420)say(a,'FALLING BACK',1.5)}}}
export function drawAlly(ctx,a,iso){let[sx,sy]=iso(a.x,a.y),death=Math.min(1,a.deathTimer/a.deathDuration),s=DRAW_SCALE;ctx.save();ctx.translate(sx,sy+death*7);ctx.globalAlpha=a.downed?0.38:1-death*.88;if(a.downed){ctx.fillStyle='#d85b50';ctx.fillRect(-10,-30,20,3);ctx.fillStyle='#fff';ctx.font='900 8px system-ui';ctx.textAlign='center';ctx.fillText('DOWNED '+Math.max(0,Math.ceil(a.downDuration-a.downTimer))+'s',0,-35)}if(!a.dead&&!a.downed&&a.hp<a.maxHp){ctx.fillStyle='#111';ctx.fillRect(-9,-28,18,3);ctx.fillStyle='#58a8ff';ctx.fillRect(-9,-28,18*Math.max(0,a.hp/a.maxHp),3)}if(a.hit>0&&!a.dead&&!a.downed){ctx.globalAlpha=.55;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,-13,10,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1-death*.88}if(a.dead){ctx.rotate(death*1.5);ctx.scale(1-death*.14,1-death*.14)}const frame=a.dead||a.downed?5:a.muzzle>0?4:a.cover?3:1+Math.floor(a.t*8)%2;ctx.save();ctx.scale(a.facingX<0?-1:1,1);ctx.filter='hue-rotate(155deg) saturate(1.35)';if(sprite.complete&&sprite.naturalWidth)ctx.drawImage(sprite,frame*64,0,64,64,-32*s,-64*s,64*s,64*s);else{ctx.filter='none';ctx.fillStyle='#477da8';ctx.fillRect(-8*s,-38*s,16*s,36*s);ctx.fillStyle='#9a9d9b';ctx.beginPath();ctx.arc(0,-48*s,10*s,0,Math.PI*2);ctx.fill()}if(a.muzzle>0&&!a.dead&&!a.downed){ctx.filter='none';ctx.fillStyle='#ffe36b';ctx.beginPath();ctx.moveTo(13,-12);ctx.lineTo(21,-9);ctx.lineTo(16,-7);ctx.lineTo(18,-11);ctx.closePath();ctx.fill()}ctx.restore();ctx.fillStyle='#fff';ctx.font='800 8px system-ui';ctx.textAlign='center';ctx.textBaseline='bottom';ctx.shadowColor='#000';ctx.shadowBlur=3;ctx.fillText(a.name||'ALLY',0,-29);if(a.calloutTimer>0&&!a.dead){const text=a.callout;ctx.font='900 9px system-ui';const bw=Math.min(132,Math.max(64,text.length*6+18));const by=-56;ctx.fillStyle='#eef3ef';ctx.beginPath();ctx.moveTo(-bw/2,by-18);ctx.quadraticCurveTo(-bw/2-3,by-18,-bw/2-3,by-14);ctx.lineTo(-bw/2-3,by-2);ctx.quadraticCurveTo(-bw/2-3,by+2,-bw/2+1,by+2);ctx.lineTo(-8,by+2);ctx.lineTo(-3,by+8);ctx.lineTo(0,by+2);ctx.lineTo(bw/2-3,by+2);ctx.quadraticCurveTo(bw/2,by+2,bw/2,by+2);ctx.lineTo(bw/2,by-14);ctx.quadraticCurveTo(bw/2,by-18,bw/2-3,by-18);ctx.closePath();ctx.fill();ctx.fillStyle='#18201d';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,0,by-9)}ctx.restore()}
