const MAP_SCALE = 1.32;
function spread(items) {
  return items.map(function (item) {
    return Object.assign({}, item, {
      x: Math.round(item.x * MAP_SCALE),
      y: Math.round(item.y * MAP_SCALE),
    });
  });
}
export function createCityCoverLayout() {
  return spread([
    {
      id: "p1",
      x: -180,
      y: 520,
      asset: "barrier_long",
      coverType: "wide",
      scale: 0.26,
      w: 160,
      h: 38,
    },
    {
      id: "p2",
      x: 0,
      y: 520,
      asset: "barrier_long",
      coverType: "wide",
      scale: 0.26,
      w: 160,
      h: 38,
    },
    {
      id: "p3",
      x: 180,
      y: 520,
      asset: "barrier_long",
      coverType: "wide",
      scale: 0.26,
      w: 160,
      h: 38,
    },
    {
      id: "ml1",
      x: -280,
      y: 250,
      asset: "sandbag_long",
      coverType: "low",
      scale: 0.25,
      w: 145,
      h: 32,
    },
    {
      id: "ml2",
      x: -420,
      y: 60,
      asset: "barrier_short",
      coverType: "wide",
      scale: 0.24,
      w: 120,
      h: 34,
    },
    {
      id: "ml3",
      x: -260,
      y: -120,
      asset: "crate_stack",
      coverType: "low",
      scale: 0.24,
      w: 120,
      h: 38,
    },
    {
      id: "mr1",
      x: 280,
      y: 250,
      asset: "sandbag_crates",
      coverType: "low",
      scale: 0.24,
      w: 135,
      h: 36,
    },
    {
      id: "mr2",
      x: 420,
      y: 40,
      asset: "barrier_short",
      coverType: "wide",
      scale: 0.24,
      w: 120,
      h: 34,
    },
    {
      id: "mr3",
      x: 260,
      y: -140,
      asset: "planter",
      coverType: "low",
      scale: 0.24,
      w: 135,
      h: 36,
    },
    {
      id: "c1",
      x: 0,
      y: 210,
      asset: "barrier_small",
      coverType: "wide",
      scale: 0.22,
      w: 100,
      h: 30,
    },
    {
      id: "c2",
      x: -90,
      y: -25,
      asset: "road_blocker",
      coverType: "low",
      scale: 0.22,
      w: 95,
      h: 28,
    },
    {
      id: "c3",
      x: 105,
      y: -30,
      asset: "road_blocker",
      coverType: "low",
      scale: 0.22,
      w: 95,
      h: 28,
    },
    {
      id: "c4",
      x: 0,
      y: -260,
      asset: "sandbag_corner",
      coverType: "low",
      scale: 0.24,
      w: 135,
      h: 42,
      segments: [
        { dx: -34, dy: 0, w: 92, h: 32 },
        { dx: 38, dy: -34, w: 34, h: 92 },
      ],
    },
    {
      id: "f1",
      x: -260,
      y: -470,
      asset: "burned_sedan",
      coverType: "car",
      scale: 0.22,
      w: 150,
      h: 48,
    },
    {
      id: "f2",
      x: 250,
      y: -470,
      asset: "pickup_truck",
      coverType: "car",
      scale: 0.22,
      w: 160,
      h: 50,
    },
    {
      id: "f3",
      x: 0,
      y: -610,
      asset: "rubble_long",
      coverType: "wide",
      scale: 0.23,
      w: 165,
      h: 42,
    },
    {
      id: "l1",
      x: -560,
      y: -180,
      asset: "rubble_wall",
      coverType: "wide",
      scale: 0.22,
      w: 145,
      h: 42,
    },
    {
      id: "l2",
      x: -620,
      y: 180,
      asset: "barrier_yellow",
      coverType: "wide",
      scale: 0.23,
      w: 145,
      h: 38,
    },
    {
      id: "r1",
      x: 560,
      y: -180,
      asset: "rubble_wall",
      coverType: "wide",
      scale: 0.22,
      w: 145,
      h: 42,
    },
    {
      id: "r2",
      x: 620,
      y: 180,
      asset: "barrier_striped",
      coverType: "wide",
      scale: 0.23,
      w: 145,
      h: 38,
    },
    {
      id: "e1",
      x: -115,
      y: 85,
      asset: "sandbag_short",
      coverType: "low",
      scale: 0.22,
      w: 85,
      h: 28,
    },
    {
      id: "e2",
      x: 125,
      y: 95,
      asset: "sandbag_short",
      coverType: "low",
      scale: 0.22,
      w: 85,
      h: 28,
    },
    {
      id: "e3",
      x: -360,
      y: -330,
      asset: "rubble_small",
      coverType: "low",
      scale: 0.22,
      w: 120,
      h: 34,
    },
    {
      id: "e4",
      x: 360,
      y: -330,
      asset: "rubble_small",
      coverType: "low",
      scale: 0.22,
      w: 120,
      h: 34,
    },
  ]);
}
export function createCityProps() {
  return spread([
    { x: -760, y: 640, asset: "lamp_post", scale: 0.24 },
    { x: -520, y: 380, asset: "lamp_post", scale: 0.24 },
    { x: 760, y: 640, asset: "lamp_post", scale: 0.24 },
    { x: 520, y: 380, asset: "lamp_post", scale: 0.24 },
    { x: -720, y: -120, asset: "power_pole", scale: 0.23 },
    { x: 720, y: -120, asset: "traffic_light", scale: 0.23 },
    { x: -690, y: 40, asset: "barrels", scale: 0.22 },
    { x: 690, y: 40, asset: "barrels", scale: 0.22 },
    { x: -470, y: -550, asset: "guard_booth", scale: 0.2 },
    { x: 470, y: -550, asset: "guard_booth", scale: 0.2 },
    { x: -120, y: -720, asset: "dual_lamp", scale: 0.23 },
    { x: 120, y: -720, asset: "camera_pole", scale: 0.23 },
  ]);
}
