import { isLineBlocked,getCoverSlot } from './cover.js';
const sprite=new Image();sprite.src='./assets/bandit.svg';
const TYPES={rifleman:{hp:60,range:430,damage:8,cool:1.7,speed:98,scale:1},shotgunner:{hp:90,range:290,damage:18,cool:2.2,speed:82,scale:1.05},heavy:{hp:150,range:500,damage:14,cool:2.5,speed:58,scale:1.15}};
export function createBandits(){const specs=[
[-650,-330,'rifleman',0],[-430,-430,'shotgunner',.4],[-170,-430,'rifleman',.8],[120,-420,'heavy',1.2],[390,-390,'rifleman',1.6],[610,-210,'shotgunner',2],
[620,80,'rifleman',2.4],[500,340,'heavy',2.8],[250,430,'rifleman',3.2],[0,430,'shotgunner',3.6],[-300,430,'rifleman',4],[-560,360,'heavy',4.4]];
return specs.map(([x,y,type,t])=>{const s=TYPES[type];return{x,y,type,hp:s.hp,maxHp:s.hp,fire:s.cool*.55+t*.05,t,dead:false,deathTimer:0,deathDuration:.8,muzzle:0,hit:0,targetX:x,targetY:y,moveTimer:.4+t*.15,cover:null,speed:s.speed,facingX:x<0?1:-1,facingY:0,peek:0,scale:s.scale,damage:s.damage,range:s.range,cool:s.cool}})}
function choosePosition(e,player,covers,enemies){const available=covers.filter(c=>Math.hypot(player.x-c.x,player.y-c.y)<760&&!enemies.some(o=>o!==e&&!o.dead&&o.cover===c));if(!available.length){const dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;e.cover=null;e.targetX=player.x-dx/d*300;e.targetY=player.y-dy/d*300;return}let pool=available.filter(c=>Math.hypot(player.x-c.x,player.y-c.y)>230&&Math.hypot(player.x-c.x,player.y-c.y)<560);if(!pool.length)pool=available;pool=pool.filter(c=>Math.hypot(c.x-e.x,c.y-e.y)>80);if(!pool.length)pool=available;pool.sort((a,b)=>Math.abs(Math.hypot(player.x-a.x,player.y-a.y)-360)-Math.abs(Math.hypot(player.x-b.x,player.y-b.y)-360));const cover=pool[Math.floor(Math.random()*Math.min(3,pool.length))];e.cover=cover;const slot=getCoverSlot(cover,e,player);e.targetX=slot.x;e.targetY=slot.y}
export function updateBandits(enemies,dt,player,covers,spawnProjectile){for(const e of enemies){if(e.dead){e.deathTimer=Math.min(e.deathDuration,e.deathTimer+dt);continue}e.t+=dt;e.fire-=dt;e.muzzle=Math.max(0,e.muzzle-dt);e.hit=Math.max(0,e.hit-dt);e.peek=Math.max(0,e.peek-dt);e.moveTimer-=dt;const dist=Math.hypot(player.x-e.x,player.y-e.y),blocked=isLineBlocked(e,player,covers);if(blocked){if(e.moveTimer<=0){e.moveTimer=.5+Math.random()*.35;choosePosition(e,player,covers,enemies)}}else if(dist<220){if(e.moveTimer<=0){e.moveTimer=.25;choosePosition(e,player,covers,enemies)}}else if(e.moveTimer<=0){e.moveTimer=.7+Math.random()*.55;choosePosition(e,player,covers,enemies)}const dx=e.targetX-e.x,dy=e.targetY-e.y,d=Math.hypot(dx,dy);if(d>7){e.facingX=dx/d;e.facingY=dy/d;const speed=e.cover?e.speed:e.speed*.9;const step=Math.min(d,speed*dt);e.x+=dx/d*step;e.y+=dy/d*step}else{e.targetX=e.x;e.targetY=e.y}const lineBlocked=isLineBlocked(e,player,covers);if(e.fire<=0){e.fire=e.cool*.78+Math.random()*e.cool*.55;const ready=e.cover?d<18:dist<e.range;if(ready&&!lineBlocked){e.facingX=(player.x-e.x)/(dist||1);e.facingY=(player.y-e.y)/(dist||1);e.muzzle=.12;e.hit=0;spawnProjectile?.(e)}else if(ready&&e.cover&&lineBlocked){e.facingX=(player.x-e.x)/(dist||1);e.facingY=(player.y-e.y)/(dist||1);e.peek=.3;e.muzzle=.12;e.hit=0;spawnProjectile?.(e)}}}}
export function drawBandit(ctx,e,iso,selected){let [x,y]=iso(e.x,e.y),death=Math.min(1,e.deathTimer/e.deathDuration);if(e.peek>0&&!e.dead){const d=Math.hypot(e.facingX,e.facingY)||1;x+=e.facingX/d*18*e.peek/.3;y+=e.facingY/d*18*e.peek/.3}ctx.save();ctx.translate(x,y+death*16);ctx.globalAlpha=1-death*.88;if(selected&&!e.dead){ctx.strokeStyle='#f5d547';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-32,21*e.scale,0,Math.PI*2);ctx.stroke()}if(!e.dead){ctx.fillStyle='#111';ctx.fillRect(-22*e.scale,-67*e.scale,44*e.scale,5);ctx.fillStyle=e.type==='heavy'?'#d88c3f':e.type==='shotgunner'?'#b75bd1':'#d84b4b';ctx.fillRect(-22*e.scale,-67*e.scale,44*e.scale*Math.max(0,e.hp/e.maxHp),5)}if(e.hit>0&&!e.dead){ctx.globalAlpha=.55;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,-35,22*e.scale,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1-death*.88}if(e.dead){ctx.rotate(death*1.5);ctx.scale(1-death*.14,1-death*.14)}const frame=e.dead?5:e.muzzle>0?4:e.cover?3:1+Math.floor(e.t*8)%2;const flip=e.facingX<0?-1:1;ctx.scale(flip,1);if(sprite.complete&&sprite.naturalWidth){if(e.type==='heavy')ctx.filter='saturate(.65) brightness(.8)';else if(e.type==='shotgunner')ctx.filter='hue-rotate(245deg) saturate(1.25)';ctx.drawImage(sprite,frame*64,0,64,64,-32*e.scale,-64*e.scale,64*e.scale,64*e.scale)}else{ctx.fillStyle=e.type==='heavy'?'#5d5148':e.type==='shotgunner'?'#704d73':'#76503b';ctx.fillRect(-13*e.scale,-38*e.scale,26*e.scale,36*e.scale);ctx.fillStyle='#b77e59';ctx.beginPath();ctx.arc(0,-48*e.scale,10*e.scale,0,Math.PI*2);ctx.fill()}if(e.muzzle>0&&!e.dead){ctx.filter='none';ctx.fillStyle='#ffe36b';ctx.beginPath();ctx.moveTo(30*e.scale,-30*e.scale);ctx.lineTo(45*e.scale,-24*e.scale);ctx.lineTo(34*e.scale,-19*e.scale);ctx.lineTo(37*e.scale,-28*e.scale);ctx.closePath();ctx.fill()}ctx.restore()}
