import { isLineBlocked,getCoverSlot,getHitChance } from './cover.js?v=20260904-33';
import { weaponCopy } from './weapons.js';

var TYPES={rifleman:{weapon:'rifle',hp:60,speed:205,scale:1},shotgunner:{weapon:'shotgun',hp:90,speed:190,scale:1.05},heavy:{weapon:'lmg',hp:150,speed:160,scale:1.15},sniper:{weapon:'sniper',hp:55,speed:180,scale:.95},marksman:{weapon:'dmr',hp:75,speed:190,scale:1},smg:{weapon:'smg',hp:52,speed:235,scale:.98},pistol:{weapon:'pistol',hp:45,speed:220,scale:.95}};
var SPAWNS=[[-1130,-890],[-720,-1040],[-90,-1090],[650,-1040],[1120,-900],[1180,-360],[1200,280],[1030,880],[470,1050],[-210,1070],[-820,930],[-1190,420],[-1210,-250],[-930,-1010]];
function rand(a,b){return a+Math.random()*(b-a)}
export function createBandits(wave){wave=wave||1;var count=Math.min(SPAWNS.length,4+wave*2);return SPAWNS.slice(0,count).map(function(pos,i){var x=pos[0],y=pos[1],type='rifleman';if(wave>=2&&i%5===1)type='shotgunner';if(wave>=2&&i%6===3)type='heavy';if(wave>=3&&i%4===0)type='sniper';if(wave>=3&&i%7===4)type='marksman';if(wave>=4&&i%6===1)type='smg';if(wave>=4&&i%8===6)type='pistol';var s=TYPES[type],w=weaponCopy(s.weapon);return{x:x,y:y,type:type,weapon:w,hp:s.hp,maxHp:s.hp,fire:w.cooldown*2+i*.08,t:i*.35,dead:false,deathTimer:0,deathDuration:.8,muzzle:0,hit:0,targetX:x,targetY:y,moveTimer:.5+i*.1,spawnTimer:2.4+(i%3)*.3,cover:null,coverSlotIndex:i%3,speed:s.speed,facingX:x<0?1:-1,facingY:0,scale:s.scale,reloadTimer:0,combatState:'seeking',combatTimer:0,shotsLeft:0,coverCycles:0,coverAnchorX:x,coverAnchorY:y,exposed:false}})}
function choosePosition(e,player,covers,enemies){var available=covers.filter(function(c){return Math.hypot(player.x-c.x,player.y-c.y)<1250});if(!available.length){var dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;e.cover=null;e.exposed=true;e.combatState='seeking';e.targetX=player.x-dx/d*560;e.targetY=player.y-dy/d*560;return}var pool=available.filter(function(c){var pd=Math.hypot(player.x-c.x,player.y-c.y);return pd>430&&pd<1100});if(!pool.length)pool=available;pool=pool.filter(function(c){return Math.hypot(c.x-e.x,c.y-e.y)>110});if(!pool.length)pool=available;var desired=e.weapon.role==='precision'?980:e.weapon.role==='marksman'?830:e.weapon.role==='flanker'?500:e.weapon.role==='breach'?380:e.weapon.role==='support'?690:720;pool.sort(function(a,b){return Math.abs(Math.hypot(player.x-a.x,player.y-a.y)-desired)-Math.abs(Math.hypot(player.x-b.x,player.y-b.y)-desired)});var c=pool[Math.floor(Math.random()*Math.min(3,pool.length))];e.cover=c;var users=enemies.filter(function(o){return o!==e&&!o.dead&&o.cover===c});e.coverSlotIndex=users.length%3;var slot=getCoverSlot(c,e,player);e.coverAnchorX=slot.x;e.coverAnchorY=slot.y;e.targetX=slot.x;e.targetY=slot.y;e.combatState='seeking';e.exposed=false}
function peekPoint(e){var dir=e.coverSlotIndex===0?-1:1,amt=e.cover&&e.cover.type==='wide'?56:42;return{x:e.coverAnchorX+dir*amt,y:e.coverAnchorY}}
function enterCovered(e){e.combatState='covered';e.combatTimer=rand(.35,.7);e.exposed=false;e.targetX=e.coverAnchorX;e.targetY=e.coverAnchorY;e.coverCycles++}
function enterExposed(e){e.combatState='exposed';e.combatTimer=rand(1.15,1.9);e.shotsLeft=3+Math.floor(Math.random()*4);e.exposed=true;var p=peekPoint(e);e.targetX=p.x;e.targetY=p.y}
export function updateBandits(enemies,dt,player,covers,spawnProjectile){if(typeof window!=='undefined')window.__battleEnemies=enemies;for(var i=0;i<enemies.length;i++){var e=enemies[i];if(e.dead){e.deathTimer=Math.min(e.deathDuration,e.deathTimer+dt);continue}e.t+=dt;e.fire-=dt;e.muzzle=Math.max(0,e.muzzle-dt);e.hit=Math.max(0,e.hit-dt);if(e.spawnTimer>0){e.spawnTimer=Math.max(0,e.spawnTimer-dt);var sd=Math.hypot(player.x-e.x,player.y-e.y)||1;e.facingX=(player.x-e.x)/sd;e.facingY=(player.y-e.y)/sd;continue}
var dist=Math.hypot(player.x-e.x,player.y-e.y),blocked=isLineBlocked(e,player,covers);e.moveTimer-=dt;if(!e.cover||e.coverCycles>=3||(blocked&&e.combatState!=='exposed')){if(e.moveTimer<=0){e.moveTimer=rand(.45,.8);choosePosition(e,player,covers,enemies);e.coverCycles=0}}if(dist<280&&e.moveTimer<=0){e.moveTimer=.25;choosePosition(e,player,covers,enemies)}
var dx=e.targetX-e.x,dy=e.targetY-e.y,d=Math.hypot(dx,dy);if(d>7){e.facingX=dx/d;e.facingY=dy/d;var step=Math.min(d,e.speed*dt);e.x+=dx/d*step;e.y+=dy/d*step}else{e.targetX=e.x;e.targetY=e.y}
if(e.cover){if(e.combatState==='seeking'&&d<=12)enterCovered(e);else if(e.combatState==='covered'){e.combatTimer-=dt;e.exposed=false;e.targetX=e.coverAnchorX;e.targetY=e.coverAnchorY;if(e.combatTimer<=0&&dist<e.weapon.range*1.15)enterExposed(e)}else if(e.combatState==='exposed'){e.combatTimer-=dt;e.exposed=true;var pp=peekPoint(e);e.targetX=pp.x;e.targetY=pp.y;if(e.combatTimer<=0||e.shotsLeft<=0)enterCovered(e)}}else e.exposed=true;
var lineBlocked=isLineBlocked(e,player,covers),chance=Math.max(8,Math.min(98,getHitChance(e,player,covers)+e.weapon.accuracy));e.lastHitChance=chance;if(e.weapon.ammo<=0&&!e.weapon.reloading){e.weapon.reloading=true;e.reloadTimer=e.weapon.reload}if(e.weapon.reloading){e.reloadTimer-=dt;if(e.reloadTimer<=0){e.weapon.reloading=false;e.weapon.ammo=e.weapon.magazine}}
var canFire=dist<e.weapon.range&&!e.weapon.reloading&&(e.exposed||!e.cover)&&(!lineBlocked||e.cover);if(e.fire<=0&&canFire){e.fire=e.weapon.cooldown+Math.random()*e.weapon.cooldown*.65;e.facingX=(player.x-e.x)/(dist||1);e.facingY=(player.y-e.y)/(dist||1);e.muzzle=.13;if(e.cover&&e.combatState==='exposed')e.shotsLeft--;if(spawnProjectile&&Math.random()*100<chance)spawnProjectile(e,player,'enemy',e.weapon.damage)}}}
