import { createPlayer, drawPlayer } from './player.js?v=20260905-50';
import { createBandits, updateBandits, drawBandit } from './enemy.js?v=20260905-50';
import { createAllies, updateAllies, drawAlly } from './ally.js?v=20260905-50';
import { createCover, findCoverForPoint, getCoverSlot, drawCover, isLineBlocked } from './cover.js?v=20260905-50';
import { initKeyboard, getKeyboardMove } from './input.js';
import { initTactical } from './tactical.js?v=20260905-50';
var canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),status=document.querySelector('#status'),hint=document.querySelector('#hint'),fireButton=document.querySelector('#fire'),reloadButton=document.querySelector('#reload'),autoPlayButton=document.querySelector('#autoPlay'),pauseButton=document.querySelector('#pause'),pauseMenu=document.querySelector('#pauseMenu'),resumeButton=document.querySelector('#resumeButton'),pauseRestart=document.querySelector('#pauseRestart'),message=document.querySelector('#message'),messageTitle=document.querySelector('#messageTitle'),messageText=document.querySelector('#messageText'),messageButton=document.querySelector('#messageButton');
var W=0,H=0,dpr=1,last=0,gameOver=false,paused=false,target=null,kills=0,hitMarker=0,damagePops=[],fireHeld=false,playerHitFlash=0,autoPlay=false,autoMoveTimer=0,wave=1,waveState='active',waveTimer=0;
var world={scaleX:.25,scaleY:.125,offsetY:-40,cameraX:0,cameraY:0,minX:-2300,maxX:2300,minY:-1900,maxY:1900};
var player=createPlayer(),covers=createCover(),enemies=createBandits(wave),allies=createAllies(),projectiles=[];
initTactical();window.__battlePlayer=player;window.__battleEnemies=enemies;window.__battleAllies=allies;window.__waveDefense=true;window.__wave=wave;
function resize(){dpr=Math.min(window.devicePixelRatio||1,2);W=window.innerWidth;H=window.innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}window.addEventListener('resize',resize);resize();
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function rand(a,b){return a+Math.random()*(b-a)}
function updateCamera(){world.cameraX+=(clamp(player.x,world.minX+430,world.maxX-430)-world.cameraX)*.09;world.cameraY+=(clamp(player.y,world.minY+330,world.maxY-330)-world.cameraY)*.09}
export function iso(x,y){return[W/2+(x-world.cameraX-y+world.cameraY)*world.scaleX,H/2+(x-world.cameraX+y-world.cameraY)*world.scaleY+world.offsetY]}
function nearestEnemy(){var living=enemies.filter(function(e){return !e.dead});living.sort(function(a,b){return distance(player,a)-distance(player,b)});return living[0]||null}
function screenToWorld(sx,sy){var a=(sx-W/2)/world.scaleX+world.cameraX,b=(sy-(H/2+world.offsetY))/world.scaleY+world.cameraY;return{x:clamp((a+b)/2,world.minX,world.maxX),y:clamp((b-a)/2,world.minY,world.maxY)}}function setTarget(e){target=e;player.aimTarget=e}
function spawnProjectile(from,to,owner,damage){var dx=to.x-from.x,dy=to.y-from.y,d=Math.hypot(dx,dy)||1,tx=to.x,ty=to.y,hitDamage=damage||0,targetRef=to;if(hitDamage<=0){var miss=45+Math.min(130,d*.11),px=-dy/d,py=dx/d,side=Math.random()<.5?-1:1;tx+=px*miss*side+rand(-22,22);ty+=py*miss*side+rand(-22,22);targetRef=null}projectiles.push({x:from.x+dx/d*22,y:from.y+dy/d*22,px:from.x+dx/d*22,py:from.y+dy/d*22,tx:tx,ty:ty,life:0,maxLife:Math.min(.62,d/5200+.05),speed:6500,owner:owner,damage:hitDamage,target:targetRef,coverGrace:(from&&from.exposed)?0.12:0.05})}
function spawnEnemyProjectile(e,to,owner,damage){spawnProjectile(e,to||player,owner||'enemy',damage)}function spawnAllyProjectile(a,e,owner,damage){spawnProjectile(a,e,owner||'ally',damage)}
function updateProjectiles(dt){for(var i=projectiles.length-1;i>=0;i--){var p=projectiles[i];p.life+=dt;var dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy)||1,step=p.speed*dt,nx=d<=step?p.tx:p.x+dx/d*step,ny=d<=step?p.ty:p.y+dy/d*step;if((p.owner==='enemy'||p.owner==='ally')&&p.life>p.coverGrace&&isLineBlocked({x:p.x,y:p.y},{x:nx,y:ny},covers)){projectiles.splice(i,1);continue}p.px=p.x;p.py=p.y;p.x=nx;p.y=ny;if(d<=step||p.life>=p.maxLife){if(p.owner==='enemy'&&p.damage>0){if(!player.dead&&!player.downed)player.takeDamage(p.damage)}else if(p.owner==='ally'&&p.damage>0&&p.target&&!p.target.dead){p.target.hp=Math.max(0,p.target.hp-p.damage);p.target.hit=.18;if(p.target.hp<=0){p.target.hp=0;p.target.dead=true;p.target.deathTimer=0}}projectiles.splice(i,1)}}}
function drawProjectiles(){projectiles.forEach(function(p){var xy=iso(p.x,p.y),txy=iso(p.tx,p.ty),x=xy[0],y=xy[1],tx=txy[0],ty=txy[1],dx=tx-x,dy=ty-y,d=Math.hypot(dx,dy)||1,tracer=p.owner==='enemy'?'#ff8d62':p.owner==='ally'?'#71b9ff':'#ffe36b',tip=p.owner==='enemy'?'#ffd0a8':p.owner==='ally'?'#c8e7ff':'#fff7b0';ctx.save();ctx.globalAlpha=Math.max(.62,1-p.life/p.maxLife);ctx.strokeStyle=tracer;ctx.lineWidth=2.2;ctx.lineCap='round';ctx.shadowColor=tracer;ctx.shadowBlur=6;ctx.beginPath();ctx.moveTo(x-dx/d*34,y-dy/d*34);ctx.lineTo(x,y);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=tip;ctx.beginPath();ctx.arc(x,y,2,0,Math.PI*2);ctx.fill();ctx.restore()})}
function updateFeedback(dt){hitMarker=Math.max(0,hitMarker-dt);playerHitFlash=Math.max(0,playerHitFlash-dt);for(var i=damagePops.length-1;i>=0;i--){damagePops[i].t+=dt;if(damagePops[i].t>=.7)damagePops.splice(i,1)}}
function drawFeedback(){if(hitMarker>0){var a=Math.min(1,hitMarker/.12),x=W/2,y=H/2-28;ctx.save();ctx.globalAlpha=a;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-10,y-10);ctx.lineTo(x-3,y-3);ctx.moveTo(x+10,y-10);ctx.lineTo(x+3,y-3);ctx.moveTo(x-10,y+10);ctx.lineTo(x-3,y+3);ctx.moveTo(x+10,y+10);ctx.lineTo(x+3,y+3);ctx.stroke();ctx.restore()}damagePops.forEach(function(p){var xy=iso(p.x,p.y),a=1-p.t/.7;ctx.save();ctx.globalAlpha=a;ctx.fillStyle='#fff';ctx.font='900 14px system-ui';ctx.textAlign='center';ctx.fillText(p.value,xy[0],xy[1]-30-p.t*20);ctx.restore()});if(playerHitFlash>0&&!player.dead){ctx.save();ctx.globalAlpha=Math.min(.35,playerHitFlash/.22*.35);ctx.fillStyle='#e14b3f';ctx.fillRect(0,0,W,H);ctx.restore()}}
function reload(){if(!player.dead&&!player.downed&&!player.reloading&&player.weapon.ammo<player.weapon.magazine)player.startReload()}
function attemptFire(){if(gameOver||paused||player.reloading||player.dead||player.downed)return;var e=target&&!target.dead?target:nearestEnemy();if(!e)return;if(distance(player,e)>player.weapon.range)return;if(player.weapon.ammo<=0){reload();return}if(isLineBlocked(player,e,covers)&&!e.exposed&&!player.cover)return;var before=player.weapon.ammo,hit=player.fireAt(e);if(player.weapon.ammo<before){spawnProjectile(player,e,'player',hit?1:0);if(hit){hitMarker=.12;damagePops.push({x:e.x,y:e.y,value:Math.round(player.lastDamageTaken||player.weapon.damage+(player.damageBonus||0)),t:0});if(e.dead)kills++}}}
function chooseAutoPosition(e){var best=null,bestCover=null,bestScore=1e9,desired=Math.min(player.weapon.range*.72,760);covers.forEach(function(c){var cd=distance(player,c),ed=distance(e,c);if(cd>1250||ed<240||ed>player.weapon.range*.95)return;var slot=getCoverSlot(c,player,e),protectedSpot=isLineBlocked({x:slot.x,y:slot.y},e,[c]),score=cd+Math.abs(ed-desired)*.55+(protectedSpot?-190:180)+(c.type==='wide'?-45:0);if(score<bestScore){bestScore=score;best=slot;bestCover=c}});if(best){player.setDestination(clamp(best.x,world.minX,world.maxX),clamp(best.y,world.minY,world.maxY),bestCover);return true}return false}
function updateAutoPlayer(dt){if(!autoPlay||gameOver||paused||player.dead||player.downed)return;var e=target&&!target.dead?target:nearestEnemy();if(!e)return;if(target!==e)setTarget(e);var d=distance(player,e),blocked=isLineBlocked(player,e,covers),engage=Math.min(player.weapon.range*.86,900);if(player.weapon.ammo<=0){reload();return}autoMoveTimer-=dt;if(d>engage){if(autoMoveTimer<=0){autoMoveTimer=.45;if(!chooseAutoPosition(e)){var dx=e.x-player.x,dy=e.y-player.y,len=Math.hypot(dx,dy)||1,advance=Math.min(Math.max(100,d-engage*.78),430);player.setDestination(clamp(player.x+dx/len*advance,world.minX,world.maxX),clamp(player.y+dy/len*advance,world.minY,world.maxY),null)}}return}if(blocked||d<280){if(autoMoveTimer<=0){autoMoveTimer=.35;chooseAutoPosition(e)}if(blocked)return}if(d<=player.weapon.range)attemptFire()}
autoPlayButton.addEventListener('pointerdown',function(e){e.preventDefault();if(paused)return;autoPlay=!autoPlay;window.__autoPlay=autoPlay;autoPlayButton.classList.toggle('active',autoPlay);autoPlayButton.textContent=autoPlay?'AUTO PLAY: ON':'AUTO PLAY';if(autoPlay){fireHeld=false;fireButton.classList.remove('active');autoMoveTimer=0;player.keyboardMove=null}else player.keyboardMove=null});fireButton.addEventListener('pointerdown',function(e){e.preventDefault();if(autoPlay||paused)return;fireHeld=true;fireButton.classList.add('active');attemptFire()});window.addEventListener('pointerup',function(){fireHeld=false;fireButton.classList.remove('active')});window.addEventListener('pointercancel',function(){fireHeld=false;fireButton.classList.remove('active')});reloadButton.addEventListener('pointerdown',function(e){e.preventDefault();reload()});
function togglePause(){if(gameOver)return;paused=!paused;fireHeld=false;fireButton.classList.remove('active');pauseMenu.classList.toggle('hidden',!paused);pauseButton.textContent=paused?'▶':'Ⅱ'}pauseButton.addEventListener('pointerdown',function(e){e.preventDefault();togglePause()});resumeButton.addEventListener('pointerdown',function(e){e.preventDefault();if(paused)togglePause()});pauseRestart.addEventListener('pointerdown',function(e){e.preventDefault();reset()});messageButton.addEventListener('pointerdown',reset);
canvas.addEventListener('pointerdown',function(e){if(gameOver||paused||player.dead||player.downed||autoPlay)return;var r=canvas.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top;for(var i=0;i<enemies.length;i++){var enemy=enemies[i];if(enemy.dead)continue;var xy=iso(enemy.x,enemy.y);if(Math.hypot(sx-xy[0],sy-(xy[1]-16))<26){setTarget(enemy);return}}var p=screenToWorld(sx,sy-10),cover=findCoverForPoint(p.x,p.y,covers);if(cover){var slot=getCoverSlot(cover,player,target&&!target.dead?target:null);player.setDestination(slot.x,slot.y,cover)}else player.setDestination(p.x,p.y,null)});initKeyboard({onFire:function(){if(!autoPlay&&!paused)attemptFire()},onReload:reload});
function beginNextWave(){wave++;window.__wave=wave;enemies=createBandits(wave);window.__battleEnemies=enemies;waveState='active';waveTimer=0;target=null;player.aimTarget=null;projectiles.length=0}function finishFailure(){gameOver=true;fireHeld=false;messageTitle.textContent='DEFENSE BROKEN';messageText.textContent='The position was overrun on wave '+wave+'.';message.classList.remove('hidden')}function updateWaveDefense(dt){if(waveState==='cleared'){waveTimer-=dt;if(waveTimer<=0)beginNextWave();return}if(enemies.length&&enemies.every(function(e){return e.dead&&e.deathTimer>=e.deathDuration})){waveState='cleared';waveTimer=2.8;target=null;player.aimTarget=null}}
function reset(){player.reset();wave=1;window.__wave=wave;waveState='active';waveTimer=0;enemies=createBandits(wave);window.__battleEnemies=enemies;projectiles.length=0;damagePops.length=0;hitMarker=0;playerHitFlash=0;target=null;kills=0;fireHeld=false;autoPlay=false;window.__autoPlay=false;autoMoveTimer=0;paused=false;autoPlayButton.classList.remove('active');autoPlayButton.textContent='AUTO PLAY';gameOver=false;world.cameraX=0;world.cameraY=0;pauseMenu.classList.add('hidden');pauseButton.textContent='Ⅱ';message.classList.add('hidden')}
function update(dt){if(gameOver||paused)return;var km=getKeyboardMove();if(!autoPlay){if(km)player.setKeyboardMove({x:km.x,y:km.y});else if(player.keyboardMove)player.setKeyboardMove(null)}else if(player.keyboardMove)player.setKeyboardMove(null);player.x=clamp(player.x,world.minX,world.maxX);player.y=clamp(player.y,world.minY,world.maxY);if(fireHeld&&!autoPlay)attemptFire();updateAutoPlayer(dt);updateBandits(enemies,dt,player,covers,spawnEnemyProjectile);updateAllies(allies,dt,player,covers,enemies,spawnAllyProjectile);player.update(dt);allies.forEach(function(a){a.x=clamp(a.x,world.minX,world.maxX);a.y=clamp(a.y,world.minY,world.maxY)});enemies.forEach(function(e){e.x=clamp(e.x,world.minX,world.maxX);e.y=clamp(e.y,world.minY,world.maxY)});updateProjectiles(dt);updateFeedback(dt);updateWaveDefense(dt);updateCamera();if(window.__tacticalTick)window.__tacticalTick(dt,player,enemies);if(target&&target.dead)target=null;if(player.dead&&player.deathTimer>=player.deathDuration)finishFailure()}
function diamond(x,y,w,h,c){var p=iso(x,y);ctx.beginPath();ctx.moveTo(p[0],p[1]-h);ctx.lineTo(p[0]+w,p[1]);ctx.lineTo(p[0],p[1]+h);ctx.lineTo(p[0]-w,p[1]);ctx.closePath();ctx.fillStyle=c;ctx.fill()}function worldPoly(points,fill,stroke){ctx.beginPath();points.forEach(function(p,i){var q=iso(p[0],p[1]);if(i===0)ctx.moveTo(q[0],q[1]);else ctx.lineTo(q[0],q[1])});ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function drawBuilding(x,y,w,h,roof){var pts=[[x-w/2,y-h/2],[x+w/2,y-h/2],[x+w/2,y+h/2],[x-w/2,y+h/2]],q=pts.map(function(p){return iso(p[0],p[1])});ctx.save();ctx.shadowColor='#0008';ctx.shadowBlur=10;ctx.shadowOffsetY=6;ctx.fillStyle='#716b60';ctx.beginPath();ctx.moveTo(q[0][0],q[0][1]-24);q.slice(1).forEach(function(v){ctx.lineTo(v[0],v[1]-24)});ctx.closePath();ctx.fill();ctx.shadowColor='transparent';ctx.fillStyle=roof||'#454b49';ctx.beginPath();ctx.moveTo(q[0][0],q[0][1]-32);q.slice(1).forEach(function(v){ctx.lineTo(v[0],v[1]-32)});ctx.closePath();ctx.fill();ctx.strokeStyle='#252a29';ctx.lineWidth=1;ctx.stroke();ctx.restore()}function drawStreetLamp(x,y){var q=iso(x,y);ctx.save();ctx.strokeStyle='#252b2a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(q[0],q[1]);ctx.lineTo(q[0],q[1]-28);ctx.lineTo(q[0]+6,q[1]-33);ctx.stroke();ctx.fillStyle='#c6b979';ctx.beginPath();ctx.arc(q[0]+7,q[1]-33,2.5,0,Math.PI*2);ctx.fill();ctx.restore()}function drawCrosswalk(y){for(var x=-380;x<=380;x+=58)worldPoly([[x,y],[x+32,y],[x+32,y+13],[x,y+13]],'#d1d0c5aa')}
function drawMapDecor(){worldPoly([[world.minX,world.minY],[world.maxX,world.minY],[world.maxX,world.maxY],[world.minX,world.maxY]],'#4b514c');worldPoly([[-310,world.minY],[310,world.minY],[310,world.maxY],[-310,world.maxY]],'#414542');worldPoly([[world.minX,world.minY],[-310,world.minY],[-310,world.maxY],[world.minX,world.maxY]],'#343a3a');worldPoly([[310,world.minY],[world.maxX,world.minY],[world.maxX,world.maxY],[310,world.maxY]],'#343a3a');for(var y=world.minY+80;y<=world.maxY-50;y+=118)worldPoly([[-11,y],[11,y],[11,y+62],[-11,y+62]],'#c0a64d99');[-1500,-900,-320,300,920,1500].forEach(drawCrosswalk);var outerRows=[-1650,-1100,-550,0,550,1100,1650];outerRows.forEach(function(y){drawBuilding(-1650,y,470,330,'#404644');drawBuilding(1650,y,470,330,'#454947')});var innerRows=[-1200,-600,0,600,1200];innerRows.forEach(function(y){drawBuilding(-980,y,320,250,'#3e4442');drawBuilding(980,y,320,250,'#424744')});for(var ly=-1700;ly<=1700;ly+=360){drawStreetLamp(-430,ly);drawStreetLamp(430,ly)}}
function drawWorld(){ctx.fillStyle='#4b514c';ctx.fillRect(0,0,W,H);for(var x=world.minX;x<=world.maxX;x+=120){for(var y=world.minY;y<=world.maxY;y+=120)diamond(x,y,42,22,(Math.floor((x+y)/120)%2===0)?'#50584f':'#4a524a')}drawMapDecor();if(target&&!target.dead){var a=iso(player.x,player.y),b=iso(target.x,target.y);ctx.save();ctx.strokeStyle='#f5d54799';ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(a[0],a[1]-12);ctx.lineTo(b[0],b[1]-12);ctx.stroke();ctx.restore()}}
function drawMissionUI(){ctx.save();var boxW=Math.min(235,W-24),x=12,y=12;ctx.fillStyle='#11181de8';ctx.strokeStyle='#ffffff33';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+12,y);ctx.lineTo(x+boxW-12,y);ctx.quadraticCurveTo(x+boxW,y,x+boxW,y+12);ctx.lineTo(x+boxW,y+70);ctx.quadraticCurveTo(x+boxW,y+82,x+boxW-12,y+82);ctx.lineTo(x+12,y+82);ctx.quadraticCurveTo(x,y+82,x,y+70);ctx.lineTo(x,y+12);ctx.quadraticCurveTo(x,y,x+12,y);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#8fb7c8';ctx.font='800 10px system-ui';ctx.textAlign='left';ctx.fillText('WAVE DEFENSE',x+14,y+18);ctx.fillStyle='#fff';ctx.font='900 15px system-ui';ctx.fillText('HOLD THE BLOCK',x+14,y+41);ctx.fillStyle='#8fb7c8';ctx.font='800 10px system-ui';var alive=enemies.filter(function(e){return !e.dead}).length,line=waveState==='cleared'?'WAVE '+wave+' CLEAR  •  NEXT '+Math.max(0,waveTimer).toFixed(1)+'s':'WAVE '+wave+'  •  HOSTILES '+alive;ctx.fillText(line,x+14,y+63);ctx.restore()}
function draw(){drawWorld();drawProjectiles();var layers=covers.map(function(c){return{o:c,y:c.x+c.y,type:'cover'}}).concat(allies.map(function(a){return{o:a,y:a.x+a.y,type:'ally'}}),enemies.map(function(e){return{o:e,y:e.x+e.y,type:'enemy'}}),[{o:player,y:player.x+player.y,type:'player'}]);layers.sort(function(a,b){return a.y-b.y});layers.forEach(function(v){if(v.type==='cover')drawCover(ctx,v.o,iso);else if(v.type==='ally')drawAlly(ctx,v.o,iso);else if(v.type==='enemy')drawBandit(ctx,v.o,iso,target===v.o);else drawPlayer(ctx,v.o,iso)});drawFeedback();drawMissionUI();var aliveAllies=allies.filter(function(a){return !a.dead}).length,aliveEnemies=enemies.filter(function(e){return !e.dead}).length;status.textContent='HP '+Math.max(0,Math.ceil(player.hp))+' • '+kills+' KILLS • WAVE '+wave+' • '+aliveEnemies+' HOSTILES • '+aliveAllies+' ALLIES • '+player.weapon.ammo+'/'+player.weapon.magazine+(player.downed?' • DOWNED':'')+(player.cover?' • IN COVER':'')+(target&&!target.dead?' • TARGET LOCKED':'')+(autoPlay?' • AI PILOT':'')+(paused?' • PAUSED':'');hint.textContent=paused?'GAME PAUSED':player.downed?'WAIT FOR A REVIVE':player.dead?'SOLDIER KIA':waveState==='cleared'?'WAVE CLEAR — PREPARE FOR CONTACT':player.reloading?'RELOADING...':'Tap to move • Tap enemy to lock • Hold FIRE';if(paused){ctx.save();ctx.fillStyle='#0005';ctx.fillRect(0,0,W,H);ctx.restore()}}
function loop(t){var dt=Math.min(.033,(t-last)/1000||.016);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
