import { createPlayer, drawPlayer } from './player.js';
import { createBandits, updateBandits, drawBandit } from './enemy.js';
import { createAllies, updateAllies, drawAlly } from './ally.js';
import { createCover, findCoverForPoint, getCoverSlot, drawCover, isLineBlocked } from './cover.js';
import { initKeyboard, getKeyboardMove } from './input.js';

var canvas=document.querySelector('#game');
var ctx=canvas.getContext('2d');
var status=document.querySelector('#status');
var hint=document.querySelector('#hint');
var fireButton=document.querySelector('#fire');
var reloadButton=document.querySelector('#reload');
var autoPlayButton=document.querySelector('#autoPlay');
var restartButton=document.querySelector('#restart');
var message=document.querySelector('#message');
var messageTitle=document.querySelector('#messageTitle');
var messageText=document.querySelector('#messageText');
var messageButton=document.querySelector('#messageButton');
var W=0,H=0,dpr=1,last=0,gameOver=false,won=false,target=null,kills=0,hitMarker=0,damagePops=[],fireHeld=false,playerHitFlash=0,damageDir=0,autoPlay=false,autoMoveTimer=0;
var wave=1,waveState='active',waveTimer=0,objectiveIndex=0;
var OBJECTIVES=['CLEAR THE FIRST POSITION','PUSH THROUGH THE BLOCK','HOLD THE LINE','BREAK THE FINAL ASSAULT'];
var world={scaleX:.36,scaleY:.19,offsetY:-40,cameraX:0,cameraY:0,minX:-800,maxX:800,minY:-650,maxY:650};
var player=createPlayer();
var covers=createCover();
var enemies=createBandits(1);
var allies=createAllies();
var projectiles=[];
function resize(){dpr=Math.min(window.devicePixelRatio||1,2);W=window.innerWidth;H=window.innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
window.addEventListener('resize',resize);resize();
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function updateCamera(){world.cameraX+=(clamp(player.x,world.minX+420,world.maxX-420)-world.cameraX)*.08;world.cameraY+=(clamp(player.y,world.minY+360,world.maxY-360)-world.cameraY)*.08}
export function iso(x,y){return[W/2+(x-world.cameraX-y+world.cameraY)*world.scaleX,H/2+(x-world.cameraX+y-world.cameraY)*world.scaleY+world.offsetY]}
function nearestEnemy(){var living=enemies.filter(function(e){return !e.dead});living.sort(function(a,b){return distance(player,a)-distance(player,b)});return living[0]||null}
function screenToWorld(sx,sy){var a=(sx-W/2)/world.scaleX+world.cameraX;var b=(sy-(H/2+world.offsetY))/world.scaleY+world.cameraY;return{x:clamp((a+b)/2,world.minX,world.maxX),y:clamp((b-a)/2,world.minY,world.maxY)}}
function setTarget(e){target=e;player.aimTarget=e}
function spawnProjectile(from,to,owner,damage){var dx=to.x-from.x,dy=to.y-from.y,d=Math.hypot(dx,dy)||1;projectiles.push({x:from.x+dx/d*22,y:from.y+dy/d*22,px:from.x+dx/d*22,py:from.y+dy/d*22,tx:to.x,ty:to.y,life:0,maxLife:Math.min(.7,d/760),speed:760,owner:owner,damage:damage||0,target:to,coverGrace:.08})}
function spawnPlayerProjectile(e){spawnProjectile(player,e,'player',24)}
function spawnEnemyProjectile(e){spawnProjectile(e,player,'enemy',e.damage||8)}
function spawnAllyProjectile(a,e){spawnProjectile(a,e,'ally',12)}
function updateProjectiles(dt){for(var i=projectiles.length-1;i>=0;i--){var p=projectiles[i];p.life+=dt;var dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy)||1,step=p.speed*dt;var nx=d<=step?p.tx:p.x+dx/d*step,ny=d<=step?p.ty:p.y+dy/d*step;if((p.owner==='enemy'||p.owner==='ally')&&p.life>p.coverGrace&&isLineBlocked({x:p.x,y:p.y},{x:nx,y:ny},covers)){projectiles.splice(i,1);continue}p.px=p.x;p.py=p.y;p.x=nx;p.y=ny;if(d<=step||p.life>=p.maxLife){if(p.owner==='enemy'){if(!player.dead){player.hp=Math.max(0,player.hp-p.damage);player.hitFlash=.18;playerHitFlash=.22;damageDir=Math.atan2(p.y-player.y,p.x-player.x)}}else if(p.owner==='ally'&&p.target&&!p.target.dead){p.target.hp=Math.max(0,p.target.hp-p.damage);p.target.hit=.18;if(p.target.hp<=0){p.target.hp=0;p.target.dead=true;p.target.deathTimer=0;kills++}}projectiles.splice(i,1)}}}
function drawProjectiles(){projectiles.forEach(function(p){var xy=iso(p.x,p.y),txy=iso(p.tx,p.ty),x=xy[0],y=xy[1],tx=txy[0],ty=txy[1],dx=tx-x,dy=ty-y,d=Math.hypot(dx,dy)||1;ctx.save();ctx.strokeStyle=p.owner==='enemy'?'#ff8d62':p.owner==='ally'?'#71b9ff':'#ffe36b';ctx.lineWidth=p.owner==='enemy'?3:2.5;ctx.lineCap='round';ctx.globalAlpha=Math.max(.2,1-p.life/p.maxLife);ctx.beginPath();ctx.moveTo(x-dx/d*16,y-dy/d*16);ctx.lineTo(x,y);ctx.stroke();ctx.fillStyle=p.owner==='enemy'?'#ffd0a8':p.owner==='ally'?'#c8e7ff':'#fff7b0';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();ctx.restore()})}
function updateFeedback(dt){hitMarker=Math.max(0,hitMarker-dt);playerHitFlash=Math.max(0,playerHitFlash-dt);for(var i=damagePops.length-1;i>=0;i--){damagePops[i].t+=dt;if(damagePops[i].t>=.7)damagePops.splice(i,1)}}
function drawFeedback(){if(hitMarker>0){var a=Math.min(1,hitMarker/.12),x=W/2,y=H/2-28;ctx.save();ctx.globalAlpha=a;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-10,y-10);ctx.lineTo(x-3,y-3);ctx.moveTo(x+10,y-10);ctx.lineTo(x+3,y-3);ctx.moveTo(x-10,y+10);ctx.lineTo(x-3,y+3);ctx.moveTo(x+10,y+10);ctx.lineTo(x+3,y+3);ctx.stroke();ctx.restore()}damagePops.forEach(function(p){var xy=iso(p.x,p.y),a=1-p.t/.7;ctx.save();ctx.globalAlpha=a;ctx.fillStyle='#fff';ctx.font='900 16px system-ui';ctx.textAlign='center';ctx.fillText(p.value,xy[0],xy[1]-48-p.t*28);ctx.restore()});if(playerHitFlash>0&&!player.dead){ctx.save();ctx.globalAlpha=Math.min(.35,playerHitFlash/.22*.35);ctx.fillStyle='#e14b3f';ctx.fillRect(0,0,W,H);ctx.restore()}}
function reload(){if(!player.dead&&!player.reloading&&player.weapon.ammo<player.weapon.magazine)player.startReload()}
function attemptFire(){if(gameOver||won||player.reloading||player.dead)return;var e=target&&!target.dead?target:nearestEnemy();if(!e)return;if(distance(player,e)>player.weapon.range)return;if(player.weapon.ammo<=0){reload();return}if(isLineBlocked(player,e,covers)&&!player.cover)return;if(player.fireAt(e)){spawnPlayerProjectile(e);hitMarker=.12;damagePops.push({x:e.x,y:e.y,value:24,t:0});if(e.dead)kills++}}
function updateAutoPlayer(dt){if(!autoPlay||gameOver||won||player.dead)return;var e=target&&!target.dead?target:nearestEnemy();if(!e)return;if(target!==e)setTarget(e);var d=distance(player,e),blocked=isLineBlocked(player,e,covers);if(player.weapon.ammo<=0){reload();return}if(!blocked&&d<=player.weapon.range){attemptFire();return}autoMoveTimer-=dt;if(autoMoveTimer<=0){autoMoveTimer=.35;if(blocked||!player.cover||d<210){var best=null,bestCover=null,bestScore=1e9;covers.forEach(function(c){var cd=distance(player,c),ed=distance(e,c);if(cd>520||ed<150)return;var slot=getCoverSlot(c,player,e),score=cd+Math.abs(ed-320)*.45;if(score<bestScore){bestScore=score;best=slot;bestCover=c}});if(best)player.setDestination(best.x,best.y,bestCover);else{var dx=player.x-e.x,dy=player.y-e.y,len=Math.hypot(dx,dy)||1;player.setDestination(clamp(player.x+dx/len*70,world.minX,world.maxX),clamp(player.y+dy/len*70,world.minY,world.maxY),null)}}}}
autoPlayButton.addEventListener('pointerdown',function(e){e.preventDefault();autoPlay=!autoPlay;autoPlayButton.classList.toggle('active',autoPlay);autoPlayButton.textContent=autoPlay?'AUTO PLAY: ON':'AUTO PLAY';if(autoPlay){fireHeld=false;fireButton.classList.remove('active');autoMoveTimer=0}else player.keyboardMove=null});
fireButton.addEventListener('pointerdown',function(e){e.preventDefault();if(autoPlay)return;fireHeld=true;fireButton.classList.add('active');attemptFire()});
window.addEventListener('pointerup',function(){fireHeld=false;fireButton.classList.remove('active')});
window.addEventListener('pointercancel',function(){fireHeld=false;fireButton.classList.remove('active')});
reloadButton.addEventListener('pointerdown',function(e){e.preventDefault();reload()});
restartButton.addEventListener('pointerdown',reset);messageButton.addEventListener('pointerdown',reset);
canvas.addEventListener('pointerdown',function(e){if(gameOver||won||player.dead||autoPlay)return;var r=canvas.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top;for(var i=0;i<enemies.length;i++){var enemy=enemies[i];if(enemy.dead)continue;var xy=iso(enemy.x,enemy.y);if(Math.hypot(sx-xy[0],sy-(xy[1]-28))<40){setTarget(enemy);return}}var p=screenToWorld(sx,sy-12),cover=findCoverForPoint(p.x,p.y,covers);if(cover){var slot=getCoverSlot(cover,player,target&&!target.dead?target:null);player.setDestination(slot.x,slot.y,cover)}else player.setDestination(p.x,p.y,null)});
initKeyboard({onFire:function(){if(!autoPlay)attemptFire()},onReload:reload});
function beginNextWave(){wave++;objectiveIndex=Math.min(wave-1,OBJECTIVES.length-1);kills=0;enemies=createBandits(wave);waveState='active';waveTimer=0;target=null;player.aimTarget=null;projectiles.length=0}
function finish(win){won=win;gameOver=!win;fireHeld=false;messageTitle.textContent=win?'MISSION COMPLETE':'MISSION FAILED';messageText.textContent=win?'All four objectives completed.':'The squad was overwhelmed.';message.classList.remove('hidden')}
function updateMission(dt){if(waveState==='complete'){waveTimer-=dt;if(waveTimer<=0){if(wave<4)beginNextWave();else finish(true)}}else if(waveState==='active'&&enemies.length&&enemies.every(function(e){return e.dead&&e.deathTimer>=e.deathDuration})){waveState='complete';waveTimer=wave<4?2.2:1.2;objectiveIndex=Math.min(wave,OBJECTIVES.length-1)}}
function reset(){player.reset();wave=1;waveState='active';waveTimer=0;objectiveIndex=0;enemies=createBandits(1);allies=createAllies();projectiles.length=0;damagePops.length=0;hitMarker=0;playerHitFlash=0;target=null;kills=0;fireHeld=false;autoPlay=false;autoMoveTimer=0;autoPlayButton.classList.remove('active');autoPlayButton.textContent='AUTO PLAY';gameOver=false;won=false;world.cameraX=0;world.cameraY=0;message.classList.add('hidden')}
function update(dt){if(gameOver||won)return;var km=getKeyboardMove();if(!autoPlay){if(km)player.setKeyboardMove({x:km.x,y:km.y});else if(player.keyboardMove)player.setKeyboardMove(null)}else if(player.keyboardMove)player.setKeyboardMove(null);player.x=clamp(player.x,world.minX,world.maxX);player.y=clamp(player.y,world.minY,world.maxY);updateAutoPlayer(dt);updateBandits(enemies,dt,player,covers,spawnEnemyProjectile);updateAllies(allies,dt,player,covers,enemies,spawnAllyProjectile);if(player.hp<=0&&!player.dead)player.triggerDeath();player.update(dt);allies.forEach(function(a){a.x=clamp(a.x,world.minX,world.maxX);a.y=clamp(a.y,world.minY,world.maxY)});if(fireHeld&&!autoPlay)attemptFire();updateProjectiles(dt);updateFeedback(dt);updateMission(dt);updateCamera();if(target&&target.dead)target=null;if(player.dead&&player.deathTimer>=player.deathDuration){finish(false)}}
function diamond(x,y,w,h,c){var p=iso(x,y);ctx.beginPath();ctx.moveTo(p[0],p[1]-h);ctx.lineTo(p[0]+w,p[1]);ctx.lineTo(p[0],p[1]+h);ctx.lineTo(p[0]-w,p[1]);ctx.closePath();ctx.fillStyle=c;ctx.fill()}
function drawWorld(){ctx.fillStyle='#293238';ctx.fillRect(0,0,W,H);for(var x=world.minX;x<=world.maxX;x+=80)for(var y=world.minY;y<=world.maxY;y+=80)diamond(x,y,28,15,(x+y)%160===0?'#303a3f':'#2c353a');covers.forEach(function(c){drawCover(ctx,c,iso)});if(target&&!target.dead){var a=iso(player.x,player.y),b=iso(target.x,target.y);ctx.save();ctx.strokeStyle='#f5d54799';ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(a[0],a[1]-30);ctx.lineTo(b[0],b[1]-30);ctx.stroke();ctx.restore()}}
function drawMissionUI(){ctx.save();var boxW=Math.min(330,W-24),x=(W-boxW)/2,y=48;ctx.fillStyle='#11181dcc';ctx.strokeStyle='#ffffff33';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+12,y);ctx.lineTo(x+boxW-12,y);ctx.quadraticCurveTo(x+boxW,y,x+boxW,y+12);ctx.lineTo(x+boxW,y+46);ctx.quadraticCurveTo(x+boxW,y+58,x+boxW-12,y+58);ctx.lineTo(x+12,y+58);ctx.quadraticCurveTo(x,y+58,x,y+46);ctx.lineTo(x,y+12);ctx.quadraticCurveTo(x,y,x+12,y);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#8fb7c8';ctx.font='800 11px system-ui';ctx.textAlign='left';ctx.fillText('WAVE '+wave+'/4',x+14,y+19);ctx.fillStyle='#fff';ctx.font='900 14px system-ui';ctx.fillText(waveState==='complete'?'OBJECTIVE COMPLETE':OBJECTIVES[objectiveIndex],x+14,y+40);ctx.restore()}
function draw(){drawWorld();drawProjectiles();var actors=allies.map(function(a){return{o:a,y:a.x+a.y,type:'ally'}}).concat(enemies.map(function(e){return{o:e,y:e.x+e.y,type:'enemy'}}));actors=actors.filter(function(v){return !v.o.dead||v.o.deathTimer<v.o.deathDuration});actors.sort(function(a,b){return a.y-b.y});actors.forEach(function(v){if(v.type==='ally')drawAlly(ctx,v.o,iso);else drawBandit(ctx,v.o,iso,target===v.o)});drawPlayer(ctx,player,iso);drawFeedback();drawMissionUI();var aliveAllies=allies.filter(function(a){return !a.dead}).length,aliveEnemies=enemies.filter(function(e){return !e.dead}).length;status.textContent='HP '+Math.max(0,Math.ceil(player.hp))+' • '+kills+' KILLS • '+aliveEnemies+' HOSTILES • '+aliveAllies+' ALLIES • '+player.weapon.ammo+'/'+player.weapon.magazine+(player.cover?' • IN COVER':'')+(target&&!target.dead?' • TARGET LOCKED':'')+(autoPlay?' • AI PILOT':'');hint.textContent=player.dead?'SOLDIER DOWN':player.reloading?'RELOADING...':'Tap a position to move • Tap an enemy to lock target • Hold FIRE to shoot'}
function loop(t){var dt=Math.min(.033,(t-last)/1000||.016);last=t;update(dt);draw();requestAnimationFrame(loop)}
requestAnimationFrame(loop);
