import { WEAPONS } from './weapons.js';
import { CHARACTER_STATS, damageReductionPercent } from './combatStats.js?v=20260905-49';

var DEFAULTS={player:'rifle',Rook:'rifle',Viper:'smg',Doc:'dmr'};
var STORAGE='coverShooterLoadout';
function loadSelection(){try{return Object.assign({},DEFAULTS,JSON.parse(localStorage.getItem(STORAGE)||'{}'))}catch(e){return Object.assign({},DEFAULTS)}}
function saveSelection(v){try{localStorage.setItem(STORAGE,JSON.stringify(v))}catch(e){}window.__selectedLoadout=Object.assign({},v)}
function weaponOptions(selected){return Object.keys(WEAPONS).map(function(id){var w=WEAPONS[id];return '<option value="'+id+'"'+(id===selected?' selected':'')+'>'+w.short+' · DMG '+w.damage+' · RNG '+w.range+'</option>'}).join('')}
function row(label,key,selection){var s=CHARACTER_STATS[key]||CHARACTER_STATS.player;return '<label class="menuLoadoutRow"><span>'+label+'<small style="display:block;margin-top:3px;color:#7f9aa5;font-size:8px;letter-spacing:.5px">HP '+s.hp+' · DEF '+s.defense+' · '+damageReductionPercent(s.defense)+'% MIT</small></span><select data-loadout="'+key+'">'+weaponOptions(selection[key])+'</select></label>'}
export function initMainMenu(onPlay){var selection=loadSelection(),screen=document.getElementById('mainMenu'),home=document.getElementById('mainMenuHome'),loadout=document.getElementById('mainMenuLoadout'),play=document.getElementById('menuPlay'),open=document.getElementById('menuLoadout'),back=document.getElementById('menuBack'),rows=document.getElementById('menuLoadoutRows');window.__selectedLoadout=Object.assign({},selection);if(rows)rows.innerHTML=row('PLAYER','player',selection)+row('ROOK','Rook',selection)+row('VIPER','Viper',selection)+row('DOC','Doc',selection);if(rows)rows.addEventListener('change',function(e){var key=e.target&&e.target.dataset?e.target.dataset.loadout:null;if(!key)return;selection[key]=e.target.value;saveSelection(selection)});if(open)open.addEventListener('pointerdown',function(e){e.preventDefault();home.classList.add('hidden');loadout.classList.remove('hidden')});if(back)back.addEventListener('pointerdown',function(e){e.preventDefault();loadout.classList.add('hidden');home.classList.remove('hidden')});if(play)play.addEventListener('pointerdown',function(e){e.preventDefault();saveSelection(selection);screen.classList.add('hidden');if(onPlay)onPlay()},{once:true})}
