export const soldierSource=new Image();
soldierSource.src='./assets/rifle_soldier_sheet.png?v=20260904-33';

const SOURCE_W=1448,SOURCE_H=1086,CELL=160,COLS=8;
let runtimeAtlas=null;

const FRAME_BOXES={
  idle:[[239,16,75,140],[368,16,73,140],[494,16,71,140],[618,16,71,140],[746,16,70,140]],
  run:[[220,174,103,138],[354,174,111,137],[485,173,110,129],[612,174,106,137],[729,175,109,137],[865,178,111,134],[999,178,115,133],[1140,179,115,131]],
  lowCover:[[223,326,107,106],[359,324,106,109],[485,323,112,109],[620,328,106,103],[749,329,109,100],[880,330,108,99]],
  tallCover:[[229,454,78,124],[363,454,79,124],[497,452,79,128],[630,455,74,123],[744,452,92,129],[878,456,83,125]],
  shoot:[[221,590,92,140],[358,592,94,140],[492,592,95,138],[624,592,99,138],[763,593,127,137],[917,593,146,137]],
  crouchShoot:[[221,746,101,106],[358,747,104,104],[506,748,104,104],[665,748,140,103],[835,747,141,104]],
  standShoot:[[221,875,105,151],[364,875,105,152],[505,875,106,152],[655,875,144,151],[822,875,152,152]]
};
const ROWS={idle:0,run:1,lowCover:2,tallCover:3,shoot:4,crouchShoot:5,standShoot:6};
const FPS={idle:3,run:9,lowCover:2,tallCover:2,shoot:14,crouchShoot:13,standShoot:13};

function nowMs(){return typeof performance!=='undefined'&&performance.now?performance.now():Date.now()}
function loadImage(img){return new Promise(function(resolve){var tries=0;function ok(){img.onload=null;img.onerror=null;resolve(img)}function fail(){tries++;if(tries>=3){img.onload=null;img.onerror=null;resolve(null);return}var base=img.src.split('&retry=')[0];setTimeout(function(){img.src=base+(base.indexOf('?')>=0?'&':'?')+'retry='+Date.now()},180)}if(img.complete&&img.naturalWidth>0){resolve(img);return}img.onload=ok;img.onerror=fail})}
function bgPixel(d,p){var i=p*4,r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),bright=(r+g+b)/3;return bright>168&&(mx-mn)<88}
function cleanCell(g,x0,y0,w,h){var im=g.getImageData(x0,y0,w,h),d=im.data,total=w*h,seen=new Uint8Array(total),queue=new Int32Array(total),head=0,tail=0;function push(x,y){if(x<0||y<0||x>=w||y>=h)return;var p=y*w+x;if(seen[p]||!bgPixel(d,p))return;seen[p]=1;queue[tail++]=p}for(var x=0;x<w;x++){push(x,0);push(x,h-1)}for(var y=1;y<h-1;y++){push(0,y);push(w-1,y)}while(head<tail){var p=queue[head++],px=p%w,py=(p/w)|0,di=p*4;d[di+3]=0;push(px+1,py);push(px-1,py);push(px,py+1);push(px,py-1)}for(var j=0;j<total;j++){var k=j*4;if(d[k+3]===0)continue;var rr=d[k],gg=d[k+1],bb=d[k+2],mx=Math.max(rr,gg,bb),mn=Math.min(rr,gg,bb),br=(rr+gg+bb)/3,sat=mx-mn;if(br>220&&sat<30)d[k+3]=Math.min(d[k+3],45);else if(br>202&&sat<42)d[k+3]=Math.min(d[k+3],125)}g.putImageData(im,x0,y0)}
function buildRuntimeAtlas(){var c=document.createElement('canvas');c.width=COLS*CELL;c.height=7*CELL;var g=c.getContext('2d',{willReadFrequently:true});if(!g)throw new Error('2D canvas unavailable');var sx=soldierSource.naturalWidth/SOURCE_W,sy=soldierSource.naturalHeight/SOURCE_H;Object.keys(ROWS).forEach(function(state){var row=ROWS[state],frames=FRAME_BOXES[state];frames.forEach(function(b,col){var x=b[0]*sx,y=b[1]*sy,w=b[2]*sx,h=b[3]*sy,maxW=142,maxH=150,fit=Math.min(1,maxW/w,maxH/h),dw=w*fit,dh=h*fit,dx=col*CELL+(CELL-dw)/2,dy=row*CELL+CELL-dh-4;g.clearRect(col*CELL,row*CELL,CELL,CELL);g.drawImage(soldierSource,x,y,w,h,dx,dy,dw,dh);cleanCell(g,col*CELL,row*CELL,CELL,CELL)})});runtimeAtlas=c}

export function preloadSoldierAssets(onProgress){onProgress=onProgress||function(){};onProgress(.15,'LOADING RIFLE SOLDIER SHEET');return loadImage(soldierSource).then(function(img){if(!img){runtimeAtlas=null;onProgress(1,'SOLDIER FALLBACK READY');return null}onProgress(.68,'CLEANING SOLDIER FRAMES');try{buildRuntimeAtlas();onProgress(1,'SOLDIER ANIMATIONS READY');return runtimeAtlas}catch(e){console.warn('Soldier atlas processing fallback',e);runtimeAtlas=null;onProgress(1,'SOLDIER FALLBACK READY');return null}})}

function moving(actor){if(!actor)return false;if(actor.state==='walk'||actor.state==='run')return true;if(typeof actor.targetX==='number'&&typeof actor.targetY==='number')return Math.hypot(actor.targetX-actor.x,actor.targetY-actor.y)>8;return false}
function shooting(actor){return !!(actor&&((actor.muzzle&&actor.muzzle>0)||(actor.shootTimer&&actor.shootTimer>0)||actor.state==='shoot'))}
function lowCover(actor){return !!(actor&&actor.cover&&actor.cover.type==='low')}
export function getSoldierState(actor){if(!actor)return'idle';if(actor.dead)return'lowCover';if(actor.downed)return'lowCover';if(shooting(actor)){if(lowCover(actor))return'crouchShoot';if(actor.cover)return'shoot';return'standShoot'}if(actor.cover)return lowCover(actor)?'lowCover':'tallCover';if(moving(actor))return'run';return'idle'}
function stableFacing(actor,state){if(!actor)return 1;var now=nowMs(),fx=Number(actor.facingX)||0,fy=Number(actor.facingY)||0,screenDir=fx-fy,mag=Math.abs(screenDir),desired=screenDir<0?-1:1,isShot=state==='shoot'||state==='crouchShoot'||state==='standShoot';if(actor.__visualFacing!==-1&&actor.__visualFacing!==1)actor.__visualFacing=mag>.12?desired:1;if(mag<.22)return actor.__visualFacing;if(isShot){if(now>=(actor.__faceLockUntil||0)&&desired!==actor.__visualFacing&&mag>.34)actor.__visualFacing=desired;actor.__faceLockUntil=now+420;actor.__faceCandidate=desired;actor.__faceCandidateAt=now;return actor.__visualFacing}if(now<(actor.__faceLockUntil||0))return actor.__visualFacing;if(desired===actor.__visualFacing){actor.__faceCandidate=desired;actor.__faceCandidateAt=now;return actor.__visualFacing}if(mag<.42)return actor.__visualFacing;if(actor.__faceCandidate!==desired){actor.__faceCandidate=desired;actor.__faceCandidateAt=now;return actor.__visualFacing}if(mag>.9||now-(actor.__faceCandidateAt||now)>190){actor.__visualFacing=desired;actor.__faceLockUntil=now+260}return actor.__visualFacing}
function frameFor(actor,state){var s=state,frames=FRAME_BOXES[s]||FRAME_BOXES.idle,row=ROWS[s]||0,now=nowMs();if(actor.__lastSoldierState!==state){actor.__lastSoldierState=state;actor.__soldierStateStart=now}var elapsed=Math.max(0,(now-(actor.__soldierStateStart||now))/1000),fps=FPS[s]||4,col=Math.min(frames.length-1,Math.floor(elapsed*fps)%frames.length);return{x:col*CELL,y:row*CELL,w:CELL,h:CELL,state:s,col:col}}
function teamFilter(team){if(team==='ally')return'sepia(.45) saturate(1.55) hue-rotate(155deg) brightness(1.03)';if(team==='enemy')return'sepia(.5) saturate(1.7) hue-rotate(315deg) brightness(1.01)';return'none'}
export function drawSoldier(ctx,actor,options){options=options||{};var state=options.state||getSoldierState(actor),r=frameFor(actor,state),baseScale=options.scale==null ? .30 : options.scale,scale=baseScale*(actor&&actor.scale?actor.scale:1),dw=r.w*scale,dh=r.h*scale,flip=stableFacing(actor,state),bob=state==='run'?Math.sin(nowMs()*.018)*.65:0;ctx.save();ctx.translate(options.x||0,(options.y||0)+bob);ctx.globalAlpha=options.alpha==null?1:options.alpha;ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(0,2,Math.max(7,dw*.22),Math.max(2,dh*.05),0,0,Math.PI*2);ctx.fill();ctx.scale(flip,1);ctx.filter=teamFilter(options.team||'player');ctx.imageSmoothingEnabled=true;if(runtimeAtlas){ctx.drawImage(runtimeAtlas,r.x,r.y,r.w,r.h,-dw*.5,-dh,dw,dh)}else{ctx.filter='none';ctx.fillStyle=options.team==='enemy'?'#8b514b':options.team==='ally'?'#477da8':'#56646b';ctx.fillRect(-6,-24,12,22);ctx.fillStyle='#9b9d9a';ctx.beginPath();ctx.arc(0,-28,5,0,Math.PI*2);ctx.fill()}ctx.restore()}
export function getSoldierAtlasInfo(){return{sourceWidth:SOURCE_W,sourceHeight:SOURCE_H,cell:CELL,rows:ROWS,frameCounts:{idle:5,run:8,lowCover:6,tallCover:6,shoot:6,crouchShoot:5,standShoot:5}}}
