const zones=[{id:'alpha',name:'ALPHA',x:0,y:300,r:150,state:'CLEAR'},{id:'bravo',name:'BRAVO',x:-430,y:-40,r:145,state:'LOCKED'},{id:'charlie',name:'CHARLIE',x:430,y:-70,r:145,state:'LOCKED'},{id:'delta',name:'DELTA',x:0,y:-560,r:170,state:'LOCKED'}];
let pressure=0,pressureTimer=0,shake=0;
export function initTactical(){if(typeof window==='undefined')return;if(window.__tacticalReady)return;window.__tacticalReady=true;window.__objectiveZones=zones;window.__battlePressure=0;window.__aimDisruption=0;window.__setBattlePressure=function(v){pressure=Math.max(0,Math.min(100,v));window.__battlePressure=pressure};createHud();setInterval(function(){if(window.__battlePlayer&&window.__battleEnemies)tick(.2,window.__battlePlayer,window.__battleEnemies)},200)}
function tick(dt,player,enemies){let incoming=0,playerSuppressed=false;for(const e of enemies){if(e.dead)continue;const d=Math.hypot(e.x-player.x,e.y-player.y),range=e.range||e.weapon?.range||450;if(d<range)incoming+=Math.max(0,1-d/range)*(e.weaponPressure||e.pressure||4);if(e.muzzle>0&&d<900)playerSuppressed=true}pressure+=(incoming*dt*2-pressure)*Math.min(1,dt*1.4);if(playerSuppressed)pressure=Math.min(100,pressure+18);pressure=Math.max(0,Math.min(100,pressure));window.__battlePressure=pressure;window.__aimDisruption=pressure>70?16:pressure>45?9:0;if(player&&player.weapon){if(player.__weaponId!==player.weapon.id){player.__weaponId=player.weapon.id;player.__baseAccuracy=player.weapon.accuracy}if(player.__baseAccuracy==null)player.__baseAccuracy=player.weapon.accuracy;player.weapon.accuracy=player.__baseAccuracy-window.__aimDisruption}shake=Math.max(shake*.72,pressure>70?Math.min(5,1.2+(pressure-70)*.13):pressure>45?1.1:0);const canvas=document.getElementById('game');if(canvas&&shake>0){canvas.style.transform='translate('+((Math.random()-.5)*shake).toFixed(2)+'px,'+((Math.random()-.5)*shake).toFixed(2)+'px) rotate('+((Math.random()-.5)*shake*.045).toFixed(3)+'deg)'}else if(canvas)canvas.style.transform='';if(pressure>65&&pressureTimer<=0)pressureTimer=1.5;pressureTimer=Math.max(0,pressureTimer-dt);updateSuppressedUnits(player,enemies);updateHud(player)}
function updateSuppressedUnits(player,enemies){const allies=window.__battleAllies||[];const all=enemies.concat(allies);for(const a of all){if(a.dead||a.downed)continue;let hostileFire=false;if(a===player){hostileFire=enemies.some(function(e){return !e.dead&&e.muzzle>0&&Math.hypot(e.x-a.x,e.y-a.y)<900})}else if(enemies.indexOf(a)>=0){hostileFire=allies.some(function(o){return !o.dead&&!o.downed&&o.muzzle>0&&Math.hypot(o.x-a.x,o.y-a.y)<850})||!!(player&&!player.dead&&!player.downed&&player.shootTimer>0&&Math.hypot(player.x-a.x,player.y-a.y)<850)}else{hostileFire=enemies.some(function(e){return !e.dead&&e.muzzle>0&&Math.hypot(e.x-a.x,e.y-a.y)<850})}a.suppressed=hostileFire||pressure>78;a.suppressionLevel=a.suppressed?Math.min(100,pressure+25):Math.max(0,(a.suppressionLevel||0)-8);if(a.suppressed&&a.cover){a.targetX=a.x;a.targetY=a.y;a.moveTimer=Math.max(a.moveTimer||0,1.1)}}}
function createHud(){if(document.getElementById('tacticalHud'))return;const box=document.createElement('div');box.id='tacticalHud';box.innerHTML='<div class="tacLabel">OBJECTIVE</div><div id="tacObjective">ALPHA <span>SECURE</span></div><div id="tacPressure"><i></i><b>PRESSURE 0%</b></div>';document.getElementById('hud').appendChild(box)}
function updateHud(player){const o=document.getElementById('tacObjective'),bar=document.querySelector('#tacPressure i'),label=document.querySelector('#tacPressure b');if(!o||!bar||!label)return;let nearest=zones[0],bd=Infinity;for(const z of zones){const d=Math.hypot(player.x-z.x,player.y-z.y);if(d<bd){bd=d;nearest=z}}const inside=bd<nearest.r;o.innerHTML=nearest.name+' <span>'+(inside?'SECURING':'ADVANCE')+'</span>';bar.style.width=Math.round(pressure)+'%';label.textContent='PRESSURE '+Math.round(pressure)+'%';label.className=pressure>70?'hot':pressure>40?'warm':''}
export function drawObjectiveZones(ctx,iso,player){for(const z of zones){const p=iso(z.x,z.y),q=iso(z.x+z.r,z.y),radius=Math.abs(q[0]-p[0]);ctx.save();ctx.globalAlpha=z===zones[0] ? .18 : .10;ctx.strokeStyle='#c9d9c9';ctx.lineWidth=2;ctx.setLineDash([8,7]);ctx.beginPath();ctx.arc(p[0],p[1],radius,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d7e4d122';ctx.beginPath();ctx.arc(p[0],p[1],radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 9px system-ui';ctx.textAlign='center';ctx.fillText(z.name,p[0],p[1]-radius-5);ctx.restore()}}
export function getPressureAccuracyPenalty(){return pressure>70?-18:pressure>45?-9:0}
